"""initial schema

Revision ID: dd83c0d9f470
Revises: 
Create Date: 2026-05-31 19:03:49.370405

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd83c0d9f470'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_overrides',
    sa.Column('ref_type', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=128), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ref_type', 'ref_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('attempt_diagnoses',
    sa.Column('attempt_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('selected_choice', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    with op.batch_alter_table('attempt_diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_diagnoses_user_id'), ['user_id'], unique=False)

    op.create_table('mistake_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.String(length=128), nullable=False),
    sa.Column('problem_id', sa.String(length=128), nullable=False),
    sa.Column('attempt_at', sa.String(length=64), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('mistake_categories', sa.JSON(), nullable=False),
    sa.Column('self_note', sa.String(length=2000), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'log_id')
    )
    with op.batch_alter_table('mistake_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistake_logs_problem_id'), ['problem_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_exam', sa.String(length=32), nullable=False),
    sa.Column('days_until_exam', sa.Integer(), nullable=False),
    sa.Column('available_hours_per_day', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=True),
    sa.Column('subject_states', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_user_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('mistake_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistake_logs_problem_id'))

    op.drop_table('mistake_logs')
    with op.batch_alter_table('attempt_diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_diagnoses_user_id'))

    op.drop_table('attempt_diagnoses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('review_overrides')
    # ### end Alembic commands ###
