"""Phase 4 확장: 시드 용어를 15 → 100으로 확장.

기존 Phase 2의 15개는 유지하고 85개를 추가. 같은 term_id가 이미 있으면 덮어쓰기.
모든 항목 review_status=ai_draft. 회계사/세무사 검수 후 expert_reviewed로 승급.

분포:
  accounting/financial_assets, revenue, leases, employee_benefits, business_combination, equity 등 17개
  accounting/cost_management 12개
  tax/income_tax, corporate_tax, vat 16개
  business/financial_management 14 + management_strategy 3
  economics/micro, macro 13개
  corporate_law 10개

전부 self_generated, ai_draft. 정의는 CPA 1차 응시 수준에 맞춤.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "seeds" / "terms"


def _term(
    term_id: str,
    name_ko: str,
    *,
    name_en: str | None = None,
    aliases: list[str] | None = None,
    subject: str,
    unit: str | None,
    definition: str,
    formula: str | None = None,
    difficulty: str,
    confusable_with: list[dict] | None = None,
    prerequisite_terms: list[str] | None = None,
    example: str | None = None,
    rights_status: str = "self_generated",
) -> dict:
    return {
        "term_id": term_id,
        "name_ko": name_ko,
        "name_en": name_en,
        "aliases": aliases or [],
        "subject": subject,
        "unit": unit,
        "definition": definition,
        "formula": formula,
        "difficulty": difficulty,
        "confusable_with": confusable_with or [],
        "prerequisite_terms": prerequisite_terms or [],
        "example": example,
        "rights_status": rights_status,
        "review_status": "ai_draft",
    }


NEW_TERMS: list[dict] = [
    # ─────────────── accounting / 재무회계 (17개) ───────────────
    _term("fair-value", "공정가치", name_en="fair value", aliases=["FV"],
          subject="accounting", unit="financial_assets",
          definition="자발적 거래에서 자산을 매도하거나 부채를 이전할 때 받거나 지급하는 가격. 시장가치가 1순위(Level 1), 관찰 가능한 입력이 2순위(Level 2), 모델 추정이 3순위(Level 3).",
          difficulty="intermediate",
          confusable_with=[{"term_id": "amortized-cost", "reason": "측정 기준이 달라 평가손익 위치(당기손익 vs 기타포괄손익)가 갈린다"}],
          example="상장주식은 종가(Level 1)로, 비상장채권은 동종 거래(Level 2)로 측정"),
    _term("revenue-recognition-5-step", "수익인식 5단계", name_en="5-step revenue model",
          aliases=["5단계 모형"], subject="accounting", unit="revenue",
          definition="K-IFRS 1115호의 수익인식 절차. 계약 식별 → 수행의무 식별 → 거래가격 산정 → 거래가격 배분 → 수행의무 이행 시점에 인식.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "performance-obligation", "reason": "5단계 중 2단계가 수행의무 식별이며 한 계약에 여러 수행의무가 있을 수 있다"}],
          example="휴대폰 + 통신서비스 묶음 판매는 2개 수행의무로 분리해 각각 인식"),
    _term("performance-obligation", "수행의무", name_en="performance obligation",
          aliases=["PO"], subject="accounting", unit="revenue",
          definition="계약에서 고객에게 약속한 구별되는 재화나 용역. 각 수행의무에 거래가격이 배분되고 이행 시점에 매출이 인식된다.",
          difficulty="intermediate",
          prerequisite_terms=["revenue-recognition-5-step"],
          confusable_with=[{"term_id": "contract-asset", "reason": "수행의무 이행 후 미청구한 권리가 계약자산이며 이행 자체는 수행의무"}],
          example="2년 SaaS 계약은 한 시점이 아니라 기간에 걸쳐 수행의무를 이행"),
    _term("contract-asset", "계약자산", name_en="contract asset",
          aliases=[], subject="accounting", unit="revenue",
          definition="기업이 수행을 완료했지만 청구 권리가 무조건적이지 않은 자산. 시간이 지나면 매출채권으로 전환된다.",
          difficulty="advanced",
          confusable_with=[{"term_id": "contract-liability", "reason": "계약자산은 수행은 했지만 청구 전, 계약부채는 청구는 했지만 수행 전(선수금 성격)"}],
          example="장기 건설계약에서 단계 진행률로 인식한 매출 중 미청구분"),
    _term("contract-liability", "계약부채", name_en="contract liability",
          aliases=[], subject="accounting", unit="revenue",
          definition="대가를 받았거나 받기로 한 시점이 수행보다 앞설 때 인식하는 부채. 수행이 완료되면 매출로 대체된다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "contract-asset", "reason": "방향이 정반대 — 계약부채는 받은 돈이 매출 전이라 부채로 잡힘"}],
          example="2년 SaaS 선결제 1,200만원은 매출 시점 도래 전까지 계약부채"),
    _term("lease-right-of-use", "사용권자산", name_en="right-of-use asset",
          aliases=["ROU"], subject="accounting", unit="leases",
          definition="K-IFRS 1116호에 따라 리스이용자가 인식하는 자산. 리스부채 + 선급리스료 + 직접원가 - 인센티브로 측정한다.",
          formula="사용권자산 = 리스부채 + 선급리스료 + 직접원가 - 인센티브",
          difficulty="advanced",
          prerequisite_terms=["lease-liability"],
          confusable_with=[{"term_id": "lease-liability", "reason": "동일 거래의 양면 — 사용권자산은 차변, 리스부채는 대변에서 인식"}],
          example="3년 사무실 임차 시 임차료 현가를 사용권자산으로 자본화하고 감가상각"),
    _term("lease-liability", "리스부채", name_en="lease liability",
          aliases=[], subject="accounting", unit="leases",
          definition="잔여 리스료를 내재이자율(또는 증분차입이자율)로 할인한 현재가치. 매기 이자비용이 가산되고 지급 시 감소한다.",
          formula="리스부채 = Σ (리스료 / (1 + r)^n)",
          difficulty="advanced",
          confusable_with=[{"term_id": "lease-right-of-use", "reason": "리스부채는 채무, 사용권자산은 자산. 측정 시점에서 동일하지만 이후 추적 경로가 다르다"}],
          example="연 1,000만원 3년 리스를 5% 할인 → 약 2,723만원이 최초 리스부채"),
    _term("impairment-loss", "손상차손", name_en="impairment loss",
          aliases=[], subject="accounting", unit="financial_assets",
          definition="자산의 회수가능액이 장부금액보다 낮을 때 인식하는 차손. 회수가능액은 순공정가치와 사용가치 중 큰 값.",
          formula="손상차손 = 장부금액 - max(순공정가치, 사용가치)",
          difficulty="intermediate",
          confusable_with=[{"term_id": "revaluation-surplus", "reason": "손상차손은 당기손익(역방향), 재평가잉여금은 기타포괄손익(상방)"}],
          example="장부 1억, 회수가능액 7천만원 → 손상차손 3천만원"),
    _term("revaluation-surplus", "재평가잉여금", name_en="revaluation surplus",
          aliases=[], subject="accounting", unit="equity",
          definition="유형자산 등을 재평가모형으로 측정해 장부금액이 증가한 부분을 기타포괄손익으로 인식한 자본 항목.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "impairment-loss", "reason": "재평가잉여금은 상방 평가(자본), 손상차손은 하방 평가(당기손익) — 반대 방향"}],
          example="공장 장부 5억을 7억으로 재평가 시 2억이 기타포괄손익 → 재평가잉여금"),
    _term("defined-benefit-obligation", "확정급여채무", name_en="defined benefit obligation",
          aliases=["DBO"], subject="accounting", unit="employee_benefits",
          definition="K-IFRS 1019호에 따라 종업원이 제공한 근무용역의 결과로 미래에 지급할 퇴직급여의 현재가치. 보험수리적 가정으로 측정.",
          difficulty="advanced",
          confusable_with=[{"term_id": "defined-contribution", "reason": "확정급여는 기업이 미래 지급액 책임, 확정기여는 매기 기여금 납부로 책임 종료"}],
          example="평균임금 × 근속연수 × 지급률로 추정한 미래 퇴직금의 현재가치"),
    _term("share-based-payment", "주식기준보상", name_en="share-based payment",
          aliases=["SBP"], subject="accounting", unit="equity",
          definition="기업이 재화/용역의 대가로 자기지분상품 또는 그 가치 기반 현금을 지급하는 거래. 부여일 공정가치로 측정하고 가득기간에 안분.",
          difficulty="advanced",
          confusable_with=[{"term_id": "dilutive-eps", "reason": "주식기준보상은 측정/인식 이슈, 희석주당이익은 결과 지표 산출 이슈"}],
          example="임직원 스톡옵션 1,000주를 부여일 공정가치 1만원으로 측정 → 가득기간에 인건비 인식"),
    _term("dilutive-eps", "희석주당이익", name_en="diluted EPS",
          aliases=["희석EPS", "diluted earnings per share"], subject="accounting", unit="equity",
          definition="모든 잠재적 보통주가 발행되었다고 가정해 산출한 EPS. 기본주당이익보다 항상 작거나 같으며 차이만큼 희석 위험을 나타낸다.",
          formula="희석EPS = (당기순이익 + 잠재주식 조정) / (가중평균유통주식수 + 잠재주식수)",
          difficulty="advanced",
          confusable_with=[{"term_id": "basic-eps", "reason": "기본EPS는 현재 유통주식만, 희석EPS는 전환사채/스톡옵션 등 잠재주식 포함"}],
          example="전환사채 행사 시 발행될 주식까지 분모에 포함해 산출"),
    _term("basic-eps", "기본주당이익", name_en="basic EPS",
          aliases=["기본EPS"], subject="accounting", unit="equity",
          definition="당기순이익을 가중평균유통보통주식수로 나눈 값. 우선주배당금을 차감 후 산출.",
          formula="기본EPS = (당기순이익 - 우선주배당) / 가중평균유통보통주식수",
          difficulty="intermediate",
          confusable_with=[{"term_id": "dilutive-eps", "reason": "기본EPS는 현재 발행주식 기준, 희석EPS는 잠재주식까지 가정"}],
          example="순이익 100억, 보통주 1억주 → 기본EPS 100원"),
    _term("equity-method", "지분법", name_en="equity method",
          aliases=[], subject="accounting", unit="business_combination",
          definition="중대한 영향력(통상 지분 20~50%)이 있는 관계기업에 적용. 취득원가에서 출발해 피투자기업 순이익의 지분만큼 가산, 배당 시 차감.",
          difficulty="advanced",
          confusable_with=[{"term_id": "consolidation", "reason": "지분법은 한 줄 표시(투자주식), 연결은 자산/부채를 줄별로 통합"}],
          example="40% 지분 보유 회사의 순이익 100억 → 40억을 지분법이익으로 인식"),
    _term("consolidation", "연결재무제표", name_en="consolidation",
          aliases=["연결"], subject="accounting", unit="business_combination",
          definition="지배기업과 종속기업을 하나의 경제실체로 보고 자산/부채/손익을 합산해 작성한 재무제표. 내부거래는 제거한다.",
          difficulty="advanced",
          prerequisite_terms=["equity-method"],
          confusable_with=[{"term_id": "equity-method", "reason": "연결은 100% 합산 후 비지배지분 분리, 지분법은 지분율만큼 한 줄로 반영"}],
          example="지분 80%인 종속기업 자산을 100% 합산 + 20% 비지배지분 표시"),
    _term("business-combination", "사업결합", name_en="business combination",
          aliases=[], subject="accounting", unit="business_combination",
          definition="취득자가 하나 이상의 사업에 대해 지배력을 획득하는 거래. K-IFRS 1103호에 따라 취득법(공정가치 측정 + 영업권 인식)을 적용.",
          difficulty="advanced",
          confusable_with=[{"term_id": "goodwill", "reason": "사업결합은 거래 자체, 영업권은 그 결과로 발생하는 차액 항목"}],
          example="A사가 B사를 인수해 B사 통제권을 획득하면 사업결합"),
    _term("goodwill", "영업권", name_en="goodwill",
          aliases=[], subject="accounting", unit="business_combination",
          definition="사업결합 시 이전대가와 식별가능 순자산 공정가치의 차액. 상각하지 않고 매년 손상검사를 수행한다.",
          formula="영업권 = 이전대가 - 식별가능 순자산 공정가치 × 지분율",
          difficulty="advanced",
          prerequisite_terms=["business-combination"],
          confusable_with=[{"term_id": "impairment-loss", "reason": "영업권은 상각이 아니라 매년 손상검사로만 평가됨"}],
          example="100억에 인수 + 순자산 공정가치 70억 → 영업권 30억"),
    # ─────────────── accounting / 원가관리 (12개) ───────────────
    _term("variable-costing", "변동원가계산", name_en="variable costing",
          aliases=["직접원가계산"], subject="accounting", unit="cost_management",
          definition="제품원가에 변동제조원가만 포함하고 고정제조원가는 기간비용으로 처리하는 방법. 의사결정과 CVP 분석에 유리.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "absorption-costing", "reason": "변동원가는 고정제조원가를 기간비용으로, 전부원가는 제품원가로 → 기말재고 평가와 순이익이 달라짐"}],
          example="변동제조원가 50, 고정제조원가 30 → 변동원가계산에서는 제품원가 50만 인식"),
    _term("absorption-costing", "전부원가계산", name_en="absorption costing",
          aliases=["흡수원가계산"], subject="accounting", unit="cost_management",
          definition="변동제조원가와 고정제조원가를 모두 제품원가에 포함시키는 방법. 외부재무보고용 GAAP 표준.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "variable-costing", "reason": "전부원가는 GAAP 기준 외부보고용, 변동원가는 내부 의사결정용"}],
          example="고정제조원가 30이 단위당 3씩 제품에 배부되어 재고 평가에 반영"),
    _term("cvp-analysis", "CVP 분석", name_en="cost-volume-profit analysis",
          aliases=["원가조업도이익분석"], subject="accounting", unit="cost_management",
          definition="원가, 조업도, 이익의 관계를 분석해 손익분기점과 목표이익 달성 조업도를 산출하는 기법.",
          formula="영업이익 = (단가 - 단위당 변동원가) × 판매량 - 고정원가",
          difficulty="intermediate",
          prerequisite_terms=["contribution-margin"],
          confusable_with=[{"term_id": "break-even-point", "reason": "CVP는 분석 프레임 전체, 손익분기점은 CVP의 한 결과값"}],
          example="단가 100, 변동원가 60, 고정원가 4,000만원 → BEP = 100,000개"),
    _term("contribution-margin", "공헌이익", name_en="contribution margin",
          aliases=["CM"], subject="accounting", unit="cost_management",
          definition="매출액에서 변동원가를 차감한 금액. 고정원가 회수 후 이익에 기여하는 부분이다.",
          formula="공헌이익 = 매출액 - 변동원가",
          difficulty="foundational",
          confusable_with=[{"term_id": "margin-of-safety", "reason": "공헌이익은 단위/총액 절대 금액, 안전한계율은 매출액 대비 여유 비율"}],
          example="단가 100, 변동원가 60 → 단위당 공헌이익 40"),
    _term("break-even-point", "손익분기점", name_en="break-even point",
          aliases=["BEP"], subject="accounting", unit="cost_management",
          definition="총수익과 총비용이 같아 영업이익이 0이 되는 판매량 또는 매출액.",
          formula="BEP 판매량 = 고정원가 / 단위당 공헌이익",
          difficulty="foundational",
          prerequisite_terms=["contribution-margin"],
          confusable_with=[{"term_id": "margin-of-safety", "reason": "BEP는 영점, 안전한계는 현재 매출이 BEP에서 얼마나 떨어졌는지"}],
          example="고정원가 4,000 / 공헌이익 40 = BEP 100개"),
    _term("margin-of-safety", "안전한계율", name_en="margin of safety",
          aliases=["MS율"], subject="accounting", unit="cost_management",
          definition="현재 매출액이 BEP 매출액을 초과한 비율. 매출이 얼마나 떨어져도 손실로 가지 않는지 측정.",
          formula="안전한계율 = (실제매출 - BEP매출) / 실제매출",
          difficulty="intermediate",
          confusable_with=[{"term_id": "break-even-point", "reason": "BEP는 기준점, 안전한계는 그 기준에서의 여유 거리"}],
          example="실제매출 10,000, BEP매출 6,000 → 안전한계율 40%"),
    _term("relevant-cost", "관련원가", name_en="relevant cost",
          aliases=[], subject="accounting", unit="cost_management",
          definition="의사결정 대안 간에 차이가 있는 미래의 회피 가능한 원가. 매몰원가와 회피 불가능한 공통원가는 제외한다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "sunk-cost", "reason": "관련원가는 미래 대안 간 차이, 매몰원가는 이미 발생해 의사결정과 무관"}],
          example="유휴설비 활용 결정 시 추가 변동원가만 관련원가, 기존 감가상각비는 매몰"),
    _term("opportunity-cost", "기회비용", name_en="opportunity cost",
          aliases=[], subject="accounting", unit="cost_management",
          definition="대안을 선택했을 때 포기한 차선 대안의 가치. 회계 장부에는 기록되지 않지만 의사결정 분석에 반영해야 한다.",
          difficulty="foundational",
          confusable_with=[{"term_id": "sunk-cost", "reason": "기회비용은 포기한 미래 가치, 매몰원가는 회수 불가능한 과거 지출"}],
          example="유휴 공장에서 외주받기 결정 시 자체 생산 시의 이익이 기회비용"),
    _term("sunk-cost", "매몰원가", name_en="sunk cost",
          aliases=[], subject="accounting", unit="cost_management",
          definition="이미 발생해 회수할 수 없는 원가. 미래 의사결정에 영향을 주어서는 안 된다.",
          difficulty="foundational",
          confusable_with=[{"term_id": "relevant-cost", "reason": "매몰원가는 무시해야 할 원가, 관련원가는 의사결정에서 비교해야 할 원가"}],
          example="개발이 끝난 R&D 비용 5억은 출시/중단 결정에서 매몰원가"),
    _term("process-costing", "종합원가계산", name_en="process costing",
          aliases=[], subject="accounting", unit="cost_management",
          definition="연속 공정 또는 대량생산에서 사용하는 원가계산. 공정별 원가를 완성품환산량으로 나눠 단위원가를 산출.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "joint-cost", "reason": "종합원가는 단일 제품의 공정 흐름, 결합원가는 한 공정에서 동시에 나오는 다품종"}],
          example="석유 정제 같은 연속 공정에서 1, 2, 3공정별 원가를 환산량으로 안분"),
    _term("equivalent-units", "완성품환산량", name_en="equivalent units of production",
          aliases=["EUP"], subject="accounting", unit="cost_management",
          definition="기말재공품의 완성도를 반영한 완성품 단위 수. 평균법과 선입선출법(FIFO)의 산출 결과가 다르다.",
          formula="EUP = 완성품 수 + 기말재공품 수 × 완성도",
          difficulty="advanced",
          prerequisite_terms=["process-costing"],
          confusable_with=[{"term_id": "process-costing", "reason": "환산량은 종합원가계산에서 사용하는 단위 측정 수단"}],
          example="완성품 800개 + 기말재공품 200개(완성도 50%) → EUP 900개"),
    _term("price-variance", "가격차이", name_en="price variance",
          aliases=[], subject="accounting", unit="cost_management",
          definition="실제 가격과 표준 가격의 차이가 실제 수량에 적용된 차이. 구매부 책임으로 본다.",
          formula="가격차이 = (실제가격 - 표준가격) × 실제수량",
          difficulty="intermediate",
          prerequisite_terms=["standard-cost"],
          confusable_with=[{"term_id": "quantity-variance", "reason": "가격차이는 구매 단가 이슈, 수량차이는 사용량(능률) 이슈"}],
          example="표준 5,000원/kg, 실제 4,800원/kg, 실제 사용 110kg → 가격차이 -22,000(유리)"),
    _term("quantity-variance", "수량차이", name_en="quantity variance",
          aliases=["능률차이"], subject="accounting", unit="cost_management",
          definition="실제 사용량과 표준 허용량의 차이가 표준 가격에 적용된 차이. 생산부 책임으로 본다.",
          formula="수량차이 = (실제수량 - 표준수량) × 표준가격",
          difficulty="intermediate",
          prerequisite_terms=["standard-cost"],
          confusable_with=[{"term_id": "price-variance", "reason": "수량차이는 생산 능률, 가격차이는 구매 단가 — 책임 부서가 다르다"}],
          example="표준 허용량 100kg, 실제 110kg, 표준가 5,000 → 수량차이 +50,000(불리)"),
    # ─────────────── tax (16개) ───────────────
    _term("deductible-expense", "손금", name_en="deductible expense",
          aliases=["손금산입"], subject="tax", unit="corporate_tax",
          definition="법인세법상 익금에서 차감하는 비용. 사업 관련성과 통상성 요건을 충족해야 손금으로 인정.",
          formula="법인세 과세표준 = 익금 - 손금",
          difficulty="intermediate",
          confusable_with=[{"term_id": "necessary-expense", "reason": "손금은 법인세법, 필요경비는 소득세법 용어 — 인정 범위와 한도가 다르다"}],
          example="법인 차량 유류비는 업무 사용분만 손금"),
    _term("non-deductible-expense", "손금불산입", name_en="non-deductible expense",
          aliases=[], subject="tax", unit="corporate_tax",
          definition="회계상 비용이지만 세무상 손금으로 인정되지 않는 항목. 접대비 한도 초과, 벌과금, 업무무관경비 등.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "deductible-expense", "reason": "손금산입은 세무상 인정, 손금불산입은 회계상 비용이라도 세무 부인"}],
          example="법인이 낸 교통 범칙금은 손금불산입"),
    _term("taxable-income", "과세표준", name_en="taxable income",
          aliases=["과표"], subject="tax", unit="income_tax",
          definition="세율을 곱하기 직전의 세무상 소득. 종합소득금액에서 소득공제를 차감한 값.",
          formula="과세표준 = 종합소득금액 - 소득공제",
          difficulty="foundational",
          confusable_with=[{"term_id": "tax-credit", "reason": "과세표준은 세율 적용 전 금액, 세액공제는 산출된 세액에서 차감"}],
          example="종합소득금액 1억 - 소득공제 1천만원 = 과세표준 9천만원"),
    _term("tax-credit", "세액공제", name_en="tax credit",
          aliases=[], subject="tax", unit="income_tax",
          definition="산출세액에서 직접 차감하는 항목. 자녀세액공제, 의료비세액공제 등. 소득공제(과세표준 차감)와 다르다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "taxable-income", "reason": "세액공제는 세액에서 차감, 소득공제는 과세표준에서 차감 → 절감 효과가 다르다"}],
          example="자녀세액공제 15만원/명은 산출세액에서 직접 차감"),
    _term("earned-income", "근로소득", name_en="earned income",
          aliases=[], subject="tax", unit="income_tax",
          definition="고용관계에서 근로의 대가로 받은 모든 소득. 근로소득공제를 차감해 근로소득금액 산정.",
          difficulty="foundational",
          confusable_with=[{"term_id": "business-income", "reason": "근로소득은 고용관계 종속적 노동, 사업소득은 독립적 영업 활동"}],
          example="월급, 상여, 수당 등이 근로소득"),
    _term("business-income", "사업소득", name_en="business income",
          aliases=[], subject="tax", unit="income_tax",
          definition="사업에서 발생하는 총수입금액에서 필요경비를 차감한 소득.",
          formula="사업소득금액 = 총수입금액 - 필요경비",
          difficulty="foundational",
          prerequisite_terms=["necessary-expense"],
          confusable_with=[{"term_id": "earned-income", "reason": "사업소득은 독립 영업, 근로소득은 고용 종속"}],
          example="음식점 운영, 프리랜서 보수 등이 사업소득"),
    _term("interest-income", "이자소득", name_en="interest income",
          aliases=[], subject="tax", unit="income_tax",
          definition="예금/적금/채권 등에서 발생하는 이자. 일반적으로 14% 원천징수되고 금융소득 종합과세 기준 초과 시 합산.",
          difficulty="foundational",
          confusable_with=[{"term_id": "dividend-income", "reason": "이자소득은 부채성 자산의 대가, 배당소득은 주식 등 자본성 자산의 대가"}],
          example="정기예금 이자 100만원은 14% 원천징수 후 86만원 수령"),
    _term("dividend-income", "배당소득", name_en="dividend income",
          aliases=[], subject="tax", unit="income_tax",
          definition="법인이 주주에게 분배한 이익 또는 잉여금. 14% 원천징수, 금융소득 종합과세 시 gross-up 적용.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "interest-income", "reason": "배당소득은 자기자본 대가(주주), 이자소득은 타인자본 대가(채권자)"}],
          example="상장주식 배당 100만원은 14% 원천징수 후 종합과세 시 gross-up"),
    _term("capital-gains", "양도소득", name_en="capital gains",
          aliases=[], subject="tax", unit="income_tax",
          definition="부동산, 주식 등 자산의 양도로 발생하는 소득. 종합소득과 분리되어 양도소득세로 별도 과세.",
          formula="양도차익 = 양도가액 - 취득가액 - 필요경비",
          difficulty="intermediate",
          confusable_with=[{"term_id": "business-income", "reason": "양도소득은 자산 처분 1회성, 사업소득은 사업 활동의 반복 소득"}],
          example="아파트 5억에 사서 7억에 매도 → 양도차익 2억"),
    _term("financial-income-aggregation", "금융소득 종합과세", name_en="financial income aggregation",
          aliases=["금융종합과세"], subject="tax", unit="income_tax",
          definition="이자/배당 등 금융소득이 연 2,000만원을 초과할 때 초과분을 다른 종합소득과 합산해 누진세율로 과세.",
          difficulty="intermediate",
          prerequisite_terms=["comprehensive-taxation"],
          confusable_with=[{"term_id": "comprehensive-taxation", "reason": "금융종합과세는 일반 종합과세의 특수 케이스 — 금융소득에 한정된 합산 기준"}],
          example="이자 3,000만원 발생 시 2,000만원 초과분 1,000만원이 종합과세 대상"),
    _term("withholding-tax", "원천징수", name_en="withholding tax",
          aliases=[], subject="tax", unit="income_tax",
          definition="소득 지급자가 일정 비율을 미리 떼어 세무서에 납부하는 제도. 분리과세로 종결되는 경우와 종합과세 정산으로 가는 경우가 있다.",
          difficulty="foundational",
          confusable_with=[{"term_id": "separate-taxation", "reason": "원천징수는 절차, 분리과세는 그 결과 종결 여부 — 모든 원천징수가 분리과세는 아니다"}],
          example="강의료 100만원에서 3.3% 원천징수 → 33,000원 세금 차감"),
    _term("final-return", "확정신고", name_en="final tax return",
          aliases=["종합소득세 확정신고"], subject="tax", unit="income_tax",
          definition="과세기간 종료 후 다음 해 5월에 종합소득을 확정해 신고/납부하는 절차. 원천징수된 세액은 정산된다.",
          difficulty="foundational",
          confusable_with=[{"term_id": "withholding-tax", "reason": "원천징수는 사전 분납, 확정신고는 사후 합산 정산"}],
          example="프리랜서가 5월에 종합소득세를 확정신고"),
    _term("input-vat", "매입세액공제", name_en="input VAT credit",
          aliases=["매입세액"], subject="tax", unit="vat",
          definition="사업자가 매입 시 부담한 부가가치세를 매출세액에서 공제받는 권리. 세금계산서 수취가 요건.",
          formula="납부세액 = 매출세액 - 매입세액",
          difficulty="foundational",
          confusable_with=[{"term_id": "deemed-input-vat", "reason": "매입세액은 실제 부담분, 의제매입세액은 면세재 매입을 의제로 인정"}],
          example="원재료 매입 1,000만원 + 부가세 100만원 → 매입세액 100만원 공제"),
    _term("zero-rated-vat", "영세율", name_en="zero-rated VAT",
          aliases=[], subject="tax", unit="vat",
          definition="수출 등에 0% 세율을 적용하는 제도. 매출세액은 0이지만 매입세액은 환급받을 수 있다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "vat-exemption", "reason": "영세율은 매입세액 환급 가능(완전면세), 면세는 매입세액 공제 불가(불완전면세)"}],
          example="수출재 1억 매출 → 매출세액 0, 그에 대응하는 매입세액은 환급"),
    _term("vat-exemption", "면세", name_en="VAT exemption",
          aliases=["부가가치세 면세"], subject="tax", unit="vat",
          definition="기초생필품, 의료/교육 등에 부가가치세를 부과하지 않는 제도. 영세율과 달리 매입세액은 공제되지 않는다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "zero-rated-vat", "reason": "면세는 매입세액 공제 불가(불완전면세), 영세율은 매입세액 환급 가능"}],
          example="병원 진료비는 면세 → 매출 부가세 0이지만 진료 장비 매입세액도 공제 불가"),
    _term("simplified-vat-payer", "간이과세자", name_en="simplified VAT payer",
          aliases=[], subject="tax", unit="vat",
          definition="연 매출 1억400만원 미만 영세사업자에게 적용되는 간편 과세. 업종별 부가가치율로 세액을 산출하고 세금계산서 발급 의무가 다르다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "input-vat", "reason": "간이과세자는 매입세액공제가 제한적 — 정상 일반과세자와 다름"}],
          example="음식점 연매출 8천만원 사업자는 간이과세자로 신고 가능"),
    # ─────────────── business / 재무관리 (14개) ───────────────
    _term("cost-of-equity", "자기자본비용", name_en="cost of equity",
          aliases=["Re", "ke"], subject="business", unit="financial_management",
          definition="주주가 요구하는 수익률. CAPM 또는 배당평가모형으로 추정한다.",
          formula="Re = Rf + β × (Rm - Rf)  (CAPM)",
          difficulty="intermediate",
          prerequisite_terms=["capm"],
          confusable_with=[{"term_id": "wacc", "reason": "Re는 주주 요구수익률, WACC는 부채까지 가중평균한 전체 자본비용"}],
          example="Rf 3%, β 1.2, Rm 8% → Re = 3% + 1.2×5% = 9%"),
    _term("capm", "자본자산가격결정모형", name_en="CAPM",
          aliases=["CAPM"], subject="business", unit="financial_management",
          definition="기대수익률을 무위험수익률 + 시장위험프리미엄 × 베타로 설명하는 모형. 체계적 위험만 보상받는다는 가정.",
          formula="E(Ri) = Rf + βi × (E(Rm) - Rf)",
          difficulty="intermediate",
          confusable_with=[{"term_id": "wacc", "reason": "CAPM은 개별 주식의 자기자본비용 추정, WACC는 기업 전체 자본비용 가중평균"}],
          example="시장 베타 1.0인 대표지수 ETF의 기대수익률은 시장 전체 평균과 같음"),
    _term("beta", "베타", name_en="beta",
          aliases=["β"], subject="business", unit="financial_management",
          definition="주식 수익률이 시장 수익률에 얼마나 민감한지의 척도. β=1은 시장과 동일, β>1은 더 민감, β<0은 역방향.",
          formula="β = Cov(Ri, Rm) / Var(Rm)",
          difficulty="intermediate",
          prerequisite_terms=["systematic-risk"],
          confusable_with=[{"term_id": "systematic-risk", "reason": "베타는 체계적 위험의 측정치, 체계적 위험은 분산투자로 제거되지 않는 위험 자체"}],
          example="베타 1.5 주식은 시장이 10% 오를 때 평균 15% 오름"),
    _term("systematic-risk", "체계적 위험", name_en="systematic risk",
          aliases=["시장위험"], subject="business", unit="financial_management",
          definition="분산투자로 제거되지 않는 위험. 시장 전반의 경기/금리/환율 등 거시 요인에서 발생. 베타로 측정.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "unsystematic-risk", "reason": "체계적 위험은 시장 전반(분산 불가), 비체계적 위험은 개별 기업 고유(분산 가능)"}],
          example="2008 금융위기는 모든 주식에 영향 → 체계적 위험"),
    _term("unsystematic-risk", "비체계적 위험", name_en="unsystematic risk",
          aliases=["고유위험"], subject="business", unit="financial_management",
          definition="개별 기업이나 산업에 국한된 위험. 분산투자로 제거 가능. CAPM에서 보상받지 못한다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "systematic-risk", "reason": "비체계적은 분산 가능 → 보상 없음, 체계적은 분산 불가 → 시장 프리미엄 보상"}],
          example="특정 회사의 CEO 사망 같은 사건은 비체계적 위험"),
    _term("npv", "순현재가치", name_en="net present value",
          aliases=["NPV"], subject="business", unit="financial_management",
          definition="투자안의 모든 현금흐름을 할인율로 할인해 합산한 값. NPV > 0이면 채택.",
          formula="NPV = Σ CFt/(1+r)^t - 초기투자",
          difficulty="intermediate",
          confusable_with=[{"term_id": "irr", "reason": "NPV는 금액 기준, IRR은 수익률 기준 — 상호배타적 투자안 비교 시 충돌 가능"}],
          example="초기 1,000, 매년 300씩 5년 회수, r=10% → NPV ≈ 137"),
    _term("irr", "내부수익률", name_en="internal rate of return",
          aliases=["IRR"], subject="business", unit="financial_management",
          definition="NPV를 0으로 만드는 할인율. 자본비용보다 크면 채택.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "npv", "reason": "IRR은 비율, NPV는 금액 — 상호배타적 투자안에서는 NPV가 우선"}],
          example="초기 1,000, 매년 300씩 5년 → IRR ≈ 15.2%"),
    _term("payback-period", "회수기간법", name_en="payback period",
          aliases=[], subject="business", unit="financial_management",
          definition="초기 투자액을 회수하는 데 걸리는 기간. 화폐의 시간가치를 무시한다는 한계.",
          difficulty="foundational",
          confusable_with=[{"term_id": "npv", "reason": "회수기간법은 시간가치 무시, NPV는 시간가치 반영 → 회수기간만으로 의사결정 위험"}],
          example="초기 1,000, 매년 400씩 회수 → 회수기간 2.5년"),
    _term("dividend-discount-model", "배당평가모형", name_en="dividend discount model",
          aliases=["DDM"], subject="business", unit="financial_management",
          definition="주식의 가치를 미래 배당의 현재가치 합으로 보는 모형. 고든 성장모형이 단순 형태.",
          formula="P = Σ Dt / (1+r)^t",
          difficulty="intermediate",
          confusable_with=[{"term_id": "gordon-growth-model", "reason": "DDM은 일반 모형, 고든 성장모형은 일정 성장률 g 가정한 특수 형태"}],
          example="매년 1,000원 영구 배당, r=10% → 주가 = 10,000원"),
    _term("gordon-growth-model", "고든 성장모형", name_en="Gordon growth model",
          aliases=["일정성장모형"], subject="business", unit="financial_management",
          definition="배당이 일정 성장률 g로 영구 증가한다고 가정한 주식 가치평가 모형.",
          formula="P = D1 / (r - g)",
          difficulty="intermediate",
          prerequisite_terms=["dividend-discount-model"],
          confusable_with=[{"term_id": "dividend-discount-model", "reason": "고든은 DDM의 특수 형태 — 성장률이 일정해야 적용 가능"}],
          example="D1=1,000, r=10%, g=4% → P = 1,000/(0.10-0.04) ≈ 16,667"),
    _term("trade-off-theory", "상충이론", name_en="trade-off theory",
          aliases=[], subject="business", unit="financial_management",
          definition="자본구조 결정에서 부채의 절세효과와 파산비용을 trade-off로 보고 최적 부채비율이 존재한다는 이론. MM의 무관련 명제와 대비된다.",
          difficulty="advanced",
          confusable_with=[{"term_id": "mm-proposition", "reason": "MM은 자본구조 무관(완전시장), 상충이론은 세금+파산비용 고려 시 최적 부채비율 존재"}],
          example="부채가 늘수록 절세효과 + 파산비용 모두 증가 → 한계가 만나는 지점이 최적"),
    _term("option-gamma", "옵션 감마", name_en="option gamma",
          aliases=["Γ"], subject="business", unit="financial_management",
          definition="델타의 기초자산 가격에 대한 변화율. 옵션 가격의 2차 민감도이며 ATM 옵션에서 가장 크다.",
          formula="감마 = ∂(델타) / ∂(기초자산가격)",
          difficulty="advanced",
          prerequisite_terms=["option-delta"],
          confusable_with=[{"term_id": "option-delta", "reason": "델타는 1차 변화율, 감마는 그 변화율의 변화율"}],
          example="ATM 콜옵션은 기초자산 변동 시 델타 변화가 가장 커서 감마가 최대"),
    _term("duration", "듀레이션", name_en="Macaulay duration",
          aliases=["맥콜리 듀레이션"], subject="business", unit="financial_management",
          definition="채권 현금흐름의 가중평균 회수기간. 이자율 변동에 대한 채권 가격 민감도 측정의 기초.",
          difficulty="advanced",
          confusable_with=[{"term_id": "modified-duration", "reason": "맥콜리 듀레이션은 기간, 수정 듀레이션은 그 값을 (1+r)로 나눠 가격 변화율 직접 산출"}],
          example="3년 만기 채권의 듀레이션은 보통 2~3년 사이"),
    _term("modified-duration", "수정 듀레이션", name_en="modified duration",
          aliases=["MD"], subject="business", unit="financial_management",
          definition="이자율 1%p 변동 시 채권 가격이 몇 % 변하는지를 보여주는 지표. 듀레이션을 (1+r)로 나눈 값.",
          formula="MD = Duration / (1 + r)",
          difficulty="advanced",
          prerequisite_terms=["duration"],
          confusable_with=[{"term_id": "duration", "reason": "수정 듀레이션은 가격 변화율(%), 듀레이션은 시간(년)"}],
          example="MD=4.5, 금리 1%p 상승 → 채권 가격 약 4.5% 하락"),
    # ─────────────── business / 일반경영 (3개) ───────────────
    _term("porters-five-forces", "포터의 5요인 분석", name_en="Porter's five forces",
          aliases=["5 forces", "5요인"], subject="business", unit="management_strategy",
          definition="산업 매력도를 결정하는 5가지 경쟁요인 — 신규 진입 위협, 대체재 위협, 구매자 교섭력, 공급자 교섭력, 기존 경쟁자 간 경쟁 — 으로 분석하는 프레임워크.",
          difficulty="foundational",
          confusable_with=[{"term_id": "swot-analysis", "reason": "5 forces는 외부 산업구조 분석, SWOT은 내외부 통합 분석"}],
          example="항공산업은 5 forces 모두 강해 평균 수익성이 낮음"),
    _term("value-chain", "가치사슬", name_en="value chain",
          aliases=[], subject="business", unit="management_strategy",
          definition="기업이 가치를 창출하는 활동을 본원활동(생산/물류/판매/서비스)과 지원활동(인사/R&D/구매/인프라)로 분해한 프레임워크.",
          difficulty="foundational",
          confusable_with=[{"term_id": "porters-five-forces", "reason": "가치사슬은 기업 내부 활동 분석, 5 forces는 산업 외부 구조 분석"}],
          example="유통기업은 물류 활동이 핵심 가치원천 → 그 활동에 자원 집중"),
    _term("swot-analysis", "SWOT 분석", name_en="SWOT analysis",
          aliases=["SWOT"], subject="business", unit="management_strategy",
          definition="기업의 강점(Strengths), 약점(Weaknesses), 기회(Opportunities), 위협(Threats)를 정리해 전략 도출에 사용하는 프레임워크.",
          difficulty="foundational",
          confusable_with=[{"term_id": "porters-five-forces", "reason": "SWOT은 통합 분석, 5 forces는 산업 경쟁 구조에 한정"}],
          example="삼성전자 — S: 브랜드/R&D, W: 디스플레이 의존, O: AI 시장, T: 중국 경쟁사"),
    # ─────────────── economics (13개) ───────────────
    _term("consumer-surplus", "소비자잉여", name_en="consumer surplus",
          aliases=[], subject="economics", unit="micro_economics",
          definition="소비자가 지불할 의향이 있는 최대가격과 실제 지불가격의 차이. 수요곡선 아래, 시장가격 위 영역.",
          difficulty="foundational",
          confusable_with=[{"term_id": "producer-surplus", "reason": "소비자잉여는 수요곡선과 가격선 사이, 생산자잉여는 가격선과 공급곡선 사이"}],
          example="10,000원까지 낼 의향이 있었는데 7,000원에 샀다면 소비자잉여 3,000원"),
    _term("producer-surplus", "생산자잉여", name_en="producer surplus",
          aliases=[], subject="economics", unit="micro_economics",
          definition="생산자가 받은 가격과 받을 의향이 있던 최저가격(한계비용)의 차이. 시장가격 아래, 공급곡선 위 영역.",
          difficulty="foundational",
          confusable_with=[{"term_id": "consumer-surplus", "reason": "위치가 반대 — 수요/공급 곡선 기준선 차이"}],
          example="원가 5,000원짜리를 7,000원에 팔았다면 생산자잉여 2,000원"),
    _term("price-elasticity", "가격탄력성", name_en="price elasticity of demand",
          aliases=["수요의 가격탄력성"], subject="economics", unit="micro_economics",
          definition="가격 변화율에 대한 수요량 변화율의 비. 1보다 크면 탄력적, 작으면 비탄력적.",
          formula="ε = |%ΔQ / %ΔP|",
          difficulty="intermediate",
          confusable_with=[{"term_id": "income-elasticity", "reason": "가격탄력성은 가격에 대한 반응, 소득탄력성은 소득에 대한 반응"}],
          example="가격 10% 인상에 수요량 20% 감소 → ε = 2 (탄력적)"),
    _term("income-elasticity", "소득탄력성", name_en="income elasticity",
          aliases=[], subject="economics", unit="micro_economics",
          definition="소득 변화율에 대한 수요량 변화율의 비. 양수면 정상재, 음수면 열등재.",
          formula="η = %ΔQ / %ΔI",
          difficulty="intermediate",
          confusable_with=[{"term_id": "price-elasticity", "reason": "독립변수가 소득(η) vs 가격(ε) — 측정 대상이 다르다"}],
          example="소득 10% 증가에 외식 20% 증가 → η = 2 (사치재)"),
    _term("substitution-effect", "대체효과", name_en="substitution effect",
          aliases=[], subject="economics", unit="micro_economics",
          definition="가격 변동 시 상대가격 변화에 의해 수요량이 바뀌는 효과. 실질소득은 일정하게 유지한 상태에서 측정.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "income-effect", "reason": "대체효과는 상대가격 변화에 의한 부분, 소득효과는 실질구매력 변화에 의한 부분"}],
          example="커피 가격 상승 시 차로 갈아타는 것이 대체효과"),
    _term("income-effect", "소득효과", name_en="income effect",
          aliases=[], subject="economics", unit="micro_economics",
          definition="가격 변동이 실질소득을 변화시켜 수요량이 바뀌는 효과. 정상재는 양(+), 열등재는 음(-).",
          difficulty="intermediate",
          confusable_with=[{"term_id": "substitution-effect", "reason": "대체효과+소득효과 = 전체 가격효과 (슬러츠키 분해)"}],
          example="쌀 가격 하락으로 실질소득 증가 → 다른 재화 구매력 증가"),
    _term("monopoly", "독점", name_en="monopoly",
          aliases=[], subject="economics", unit="micro_economics",
          definition="단일 공급자가 시장 전체를 지배하는 구조. 가격설정자(price maker)이며 MR = MC에서 이윤극대화.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "perfect-competition", "reason": "독점은 가격설정자, 완전경쟁은 가격수용자 — 정반대"}],
          example="과거 한국전력의 전력 시장은 자연독점"),
    _term("perfect-competition", "완전경쟁", name_en="perfect competition",
          aliases=[], subject="economics", unit="micro_economics",
          definition="동질재화, 다수의 공급자/수요자, 자유로운 진입퇴출, 완전정보 가정의 시장. 가격수용자이며 P = MC에서 균형.",
          difficulty="foundational",
          confusable_with=[{"term_id": "monopoly", "reason": "P = MC(완경) vs MR = MC < P(독점) — 균형 조건이 다르다"}],
          example="농산물 시장이 완전경쟁에 가까운 예"),
    _term("gdp", "국내총생산", name_en="gross domestic product",
          aliases=["GDP"], subject="economics", unit="macro_economics",
          definition="일정 기간 한 나라 안에서 생산된 모든 최종 재화/용역의 시장가치 합계. 생산/지출/소득 3가지 접근법.",
          formula="GDP(지출) = C + I + G + (X - M)",
          difficulty="foundational",
          confusable_with=[{"term_id": "money-supply", "reason": "GDP는 실물 생산 지표, 통화량은 화폐 측면 지표"}],
          example="2024년 한국 GDP 약 2,400조원"),
    _term("is-lm-model", "IS-LM 모형", name_en="IS-LM model",
          aliases=["IS-LM"], subject="economics", unit="macro_economics",
          definition="실물시장 균형(IS)과 화폐시장 균형(LM)을 동시에 충족하는 이자율-소득 결합을 분석하는 단기 거시 모형.",
          difficulty="advanced",
          confusable_with=[{"term_id": "ad-as-model", "reason": "IS-LM은 단기 이자율-소득 평면, AD-AS는 물가-소득 평면"}],
          example="확장적 재정정책(G↑) → IS 우측 이동 → 균형 소득 증가, 이자율 상승"),
    _term("ad-as-model", "AD-AS 모형", name_en="AD-AS model",
          aliases=["AD-AS"], subject="economics", unit="macro_economics",
          definition="총수요(AD)와 총공급(AS)의 만남으로 물가와 산출 수준이 결정되는 모형. IS-LM에 노동시장을 추가한 확장.",
          difficulty="advanced",
          prerequisite_terms=["is-lm-model"],
          confusable_with=[{"term_id": "is-lm-model", "reason": "AD-AS는 물가까지 포함한 완전 모형, IS-LM은 물가 고정 가정"}],
          example="공급충격(유가 상승) → AS 좌측 이동 → 물가 상승 + 산출 감소(스태그플레이션)"),
    _term("money-supply", "통화량", name_en="money supply",
          aliases=["M1", "M2"], subject="economics", unit="macro_economics",
          definition="한 경제 내 화폐 총량. M1(현금+요구불예금), M2(M1+저축성예금) 등 정의에 따라 범위가 다르다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "monetary-policy", "reason": "통화량은 결과, 통화정책은 통화량/이자율을 조절하는 수단"}],
          example="중앙은행이 국채 매입 → 본원통화 증가 → M1, M2 확대"),
    _term("exchange-rate", "환율", name_en="exchange rate",
          aliases=[], subject="economics", unit="macro_economics",
          definition="자국 통화와 외국 통화의 교환비율. 명목환율과 실질환율(상대 물가 반영) 구분.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "money-supply", "reason": "환율은 대외 가격, 통화량은 국내 화폐 총량 — 통화 정책으로 환율 영향"}],
          example="1USD = 1,300원이면 명목환율 1,300원/달러"),
    # ─────────────── corporate_law (10개) ───────────────
    _term("merchant", "상인", name_en="merchant",
          aliases=[], subject="corporate_law", unit="commercial_general",
          definition="자기 명의로 상행위를 영업으로 하는 자(당연상인) 또는 점포 기타 유사 설비로 상인과 같은 방법으로 영업하는 자(의제상인).",
          difficulty="foundational",
          confusable_with=[{"term_id": "trade-name", "reason": "상인은 주체, 상호는 그 상인이 영업에 사용하는 명칭"}],
          example="음식점 운영자는 의제상인, 도매업자는 당연상인"),
    _term("trade-name", "상호", name_en="trade name",
          aliases=[], subject="corporate_law", unit="commercial_general",
          definition="상인이 영업상 자기를 표시하기 위해 사용하는 명칭. 등기로 보호 가능하고 부정 사용 시 사용폐지청구권이 발생.",
          difficulty="foundational",
          prerequisite_terms=["merchant"],
          confusable_with=[{"term_id": "merchant", "reason": "상인은 사람/법인, 상호는 그가 영업에 쓰는 명칭"}],
          example="'주식회사 홍길동상회' 같은 명칭이 상호"),
    _term("commercial-register", "상업등기", name_en="commercial register",
          aliases=[], subject="corporate_law", unit="commercial_general",
          definition="상인 또는 회사의 일정 사항을 공시하기 위한 등기. 등기 사항은 선의의 제3자에게 대항 가능.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "trade-name", "reason": "상업등기는 등기 행위 자체, 상호는 등기 대상 중 하나"}],
          example="회사 설립 시 본점 소재지의 법원 등기소에 상업등기 신청"),
    _term("agency-by-estoppel", "표현대리", name_en="agency by estoppel",
          aliases=["표시대리"], subject="corporate_law", unit="commercial_general",
          definition="대리권이 없거나 소멸한 자의 대리행위에 대해 본인이 대리권 외관 작출에 기여했다면 선의·무과실의 제3자에 대해 본인이 책임지는 제도.",
          difficulty="advanced",
          confusable_with=[{"term_id": "merchant", "reason": "표현대리는 대리권 외관 신뢰 보호 법리, 상인은 영업주체 — 무관 개념"}],
          example="해임된 영업부장이 명함으로 계약 → 본인이 회수 안 했다면 표현대리 성립 가능"),
    _term("board-of-directors", "이사회", name_en="board of directors",
          aliases=[], subject="corporate_law", unit="company_law",
          definition="이사 전원으로 구성되는 회사의 중요 의사결정 기관. 이사 선임/해임 외 업무집행 결정, 대표이사 선임 등 권한 보유.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "shareholders-meeting", "reason": "이사회는 업무집행기관, 주주총회는 회사 최고 의사결정기관(소유자 회의)"}],
          example="이사회는 사채 발행, 신주발행, 대표이사 선임 등을 결정"),
    _term("shareholders-meeting", "주주총회", name_en="shareholders meeting",
          aliases=["주총"], subject="corporate_law", unit="company_law",
          definition="주식회사의 최고 의사결정기관. 정관 변경, 이사 선임, 재무제표 승인 등 회사 근본 사항을 결의한다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "board-of-directors", "reason": "주총은 소유자(주주)의 회의, 이사회는 경영진의 회의"}],
          example="정기 주주총회는 매년 결산 후 3개월 이내 개최"),
    _term("statutory-auditor", "감사", name_en="statutory auditor",
          aliases=[], subject="corporate_law", unit="company_law",
          definition="이사의 직무 집행을 감독하는 회사의 기관. 주주총회에서 선임되며 회계 및 업무 감사 권한을 가진다.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "board-of-directors", "reason": "이사회는 경영 의사결정, 감사는 그 결정과 집행을 감독"}],
          example="감사는 회계장부 열람권, 이사회 출석권을 가진다"),
    _term("preemptive-right", "신주인수권", name_en="preemptive right",
          aliases=[], subject="corporate_law", unit="company_law",
          definition="기존 주주가 회사가 발행하는 신주를 자신의 지분 비율대로 우선 인수할 권리. 정관으로 제한 가능.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "dividend-payment", "reason": "신주인수권은 자본 측면 권리, 배당은 이익 분배 측면 권리"}],
          example="지분 10% 주주는 신주 1,000주 발행 시 100주 우선 인수권"),
    _term("dividend-payment", "이익배당", name_en="dividend",
          aliases=["배당"], subject="corporate_law", unit="company_law",
          definition="회사가 영업 이익에서 주주에게 지급하는 분배. 배당가능이익 한도 내에서, 주주총회 결의로 결정.",
          difficulty="foundational",
          confusable_with=[{"term_id": "preemptive-right", "reason": "배당은 이익 분배(현금/주식 흐름), 신주인수권은 신주 우선 매입 권리"}],
          example="현금배당 외 주식배당 가능 — 자본전입의 한 형태"),
    _term("corporate-reorganization", "회사 분할·합병", name_en="merger and division",
          aliases=["M&A", "합병", "분할"], subject="corporate_law", unit="company_law",
          definition="둘 이상의 회사가 하나로 합쳐지거나(합병), 한 회사가 둘 이상으로 나뉘는(분할) 조직 재편 절차. 채권자 보호와 주주 보호 절차가 핵심.",
          difficulty="advanced",
          confusable_with=[{"term_id": "shareholders-meeting", "reason": "합병/분할은 절차이며 주주총회 특별결의가 필수 단계 중 하나"}],
          example="A주식회사가 B주식회사를 흡수합병하면 B는 청산 없이 소멸"),
    # ── 추가 1: contingent-liability — provision의 confusable 활성화용 ──
    _term("contingent-liability", "우발부채", name_en="contingent liability",
          aliases=[], subject="accounting", unit="provisions",
          definition="과거 사건의 결과로 잠재적 의무가 있지만 불확실하거나 신뢰성 있는 추정이 어려워 부채로 인식하지 않고 주석에 공시하는 부채.",
          difficulty="intermediate",
          confusable_with=[{"term_id": "provision", "reason": "충당부채는 인식 요건 충족 시 재무상태표 계상, 우발부채는 주석 공시만"}],
          example="진행 중인 소송에서 패소 시 배상 가능성이 있지만 금액 추정이 어려운 경우"),
]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for term in NEW_TERMS:
        path = OUT_DIR / f"{term['term_id']}.term.json"
        with path.open("w", encoding="utf-8", newline="\n") as f:
            json.dump(term, f, ensure_ascii=False, indent=2)
            f.write("\n")
        written += 1
    print(f"wrote {written} new term files to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
