"""Phase 5: 시드를 102 → 500으로 확장 (과목당 ≈100개).

추가: accounting +61, business +80, tax +80, economics +87, corporate_law +90 = 398.
모두 ai_draft. 정의는 1~2문장 압축 + 가능한 경우 1개의 의미 있는 confusable 페어.

다음 턴에 200/과목(=1000)으로 확장 예정.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "seeds" / "terms"


def t(
    tid: str,
    ko: str,
    en: str | None,
    subj: str,
    unit: str | None,
    defn: str,
    diff: str = "intermediate",
    conf: str | None = None,
    cr: str | None = None,
    formula: str | None = None,
    aliases: list[str] | None = None,
    ex: str | None = None,
    pre: list[str] | None = None,
) -> dict:
    return {
        "term_id": tid,
        "name_ko": ko,
        "name_en": en,
        "aliases": aliases or [],
        "subject": subj,
        "unit": unit,
        "definition": defn,
        "formula": formula,
        "difficulty": diff,
        "confusable_with": [{"term_id": conf, "reason": cr}] if conf else [],
        "prerequisite_terms": pre or [],
        "example": ex,
        "rights_status": "self_generated",
        "review_status": "ai_draft",
    }


TERMS: list[dict] = [
    # ═══════════════════ accounting (+61) ═══════════════════
    # ── 재무회계 자산 분류 / 측정 (15) ──
    t("fvpl-financial-asset", "당기손익공정가치측정 금융자산", "FVPL financial asset", "accounting", "financial_assets",
      "공정가치로 측정하고 평가손익을 당기손익으로 인식하는 금융자산. 단기매매 목적 또는 SPPI 미충족 자산이 분류된다.",
      conf="amortized-cost", cr="FVPL은 평가손익을 당기손익으로, AC는 평가하지 않고 상각만"),
    t("fvoci-financial-asset", "기타포괄손익공정가치측정 금융자산", "FVOCI financial asset", "accounting", "financial_assets",
      "공정가치로 측정하되 평가손익을 기타포괄손익으로 인식하는 금융자산. 채무상품과 지분상품 분류 기준이 다르다.",
      conf="fvpl-financial-asset", cr="FVOCI는 평가손익을 기타포괄손익(자본)으로, FVPL은 당기손익으로"),
    t("trading-securities", "단기매매금융자산", "trading securities", "accounting", "financial_assets",
      "단기 차익 목적으로 보유하는 금융자산. FVPL로 분류되어 평가손익이 당기손익에 반영된다.",
      conf="fvpl-financial-asset", cr="단기매매금융자산은 FVPL의 한 종류로 분류 사유가 단기차익 목적"),
    t("sppi-test", "SPPI 요건", "SPPI test", "accounting", "financial_assets",
      "원금과 이자만으로 구성된 현금흐름(Solely Payments of Principal and Interest)인지 평가하는 기준. AC/FVOCI 분류의 필수 조건.",
      diff="advanced",
      conf="amortized-cost", cr="SPPI는 분류 요건, AC는 분류 후 측정 방법"),
    t("receivables", "매출채권", "trade receivables", "accounting", "financial_assets",
      "재화 판매 또는 용역 제공의 대가로 받을 권리. 손상은 단순화된 ECL 모형으로 측정한다.",
      diff="foundational",
      conf="contract-asset", cr="매출채권은 청구 권리가 무조건적, 계약자산은 수행은 했으나 청구 권리가 조건부"),
    t("inventory", "재고자산", "inventory", "accounting", "financial_assets",
      "정상적 영업과정에서 판매하기 위해 보유하거나 생산 중인 자산. 취득원가와 순실현가능가치 중 낮은 값으로 측정.",
      diff="foundational",
      conf="inventory-write-down", cr="재고자산은 자산 자체, 평가손실은 감액 인식 절차"),
    t("inventory-write-down", "재고자산평가손실", "inventory write-down", "accounting", "financial_assets",
      "재고자산의 순실현가능가치가 장부금액보다 낮을 때 인식하는 차손. 이후 가치 회복 시 환입 가능.",
      conf="impairment-loss", cr="재고자산평가손실은 재고에 한정, 손상차손은 비유동자산(유형/무형)에 적용"),
    t("ppe", "유형자산", "property plant and equipment", "accounting", "financial_assets",
      "재화 생산이나 용역 제공 또는 임대 목적으로 1년 초과 보유하는 물리적 자산. 토지/건물/기계장치/차량운반구 등.",
      diff="foundational",
      conf="investment-property", cr="유형자산은 자체 사용 목적, 투자부동산은 시세차익/임대수익 목적"),
    t("investment-property", "투자부동산", "investment property", "accounting", "financial_assets",
      "임대수익이나 시세차익을 얻을 목적으로 보유하는 부동산. 원가모형 또는 공정가치모형 선택.",
      conf="ppe", cr="투자부동산은 임대/시세차익 목적, 유형자산은 자체 영업 사용 목적"),
    t("intangible-asset", "무형자산", "intangible asset", "accounting", "financial_assets",
      "물리적 실체가 없으나 식별 가능하고 통제 가능하며 미래 경제적 효익이 기대되는 비화폐성 자산. 영업권은 별도.",
      conf="goodwill", cr="무형자산은 식별 가능, 영업권은 식별 불가능한 잔여 가치"),
    t("development-cost", "개발비", "development cost", "accounting", "financial_assets",
      "개발 단계에서 발생한 지출 중 6가지 자본화 요건을 모두 충족할 때 무형자산으로 인식하는 항목. 연구 단계 지출은 비용 처리.",
      diff="advanced",
      conf="research-cost", cr="개발비는 자본화 가능, 연구비는 무조건 비용"),
    t("research-cost", "연구비", "research cost", "accounting", "financial_assets",
      "새로운 과학적·기술적 지식을 얻기 위한 탐구 단계의 지출. 자본화 불가능, 발생 시 비용 처리.",
      conf="development-cost", cr="연구비는 자본화 불가, 개발비는 요건 충족 시 자본화"),
    t("biological-asset", "생물자산", "biological asset", "accounting", "financial_assets",
      "살아있는 동물 또는 식물. K-IFRS 1041호에 따라 원칙적으로 매 보고기간말 공정가치(- 매각부대원가)로 측정.",
      diff="advanced",
      conf="agricultural-produce", cr="생물자산은 살아있는 동식물, 농림어업 수확물은 분리된 시점의 산출물"),
    t("agricultural-produce", "수확물", "agricultural produce", "accounting", "financial_assets",
      "생물자산에서 수확된 산물. 수확 시점의 공정가치로 측정 후 재고자산으로 재분류된다.",
      diff="advanced",
      conf="biological-asset", cr="수확물은 분리된 산출물, 생물자산은 분리 전 살아있는 상태"),
    t("non-current-held-for-sale", "매각예정비유동자산", "non-current asset held for sale", "accounting", "financial_assets",
      "1년 내 매각이 거의 확실한 비유동자산. 장부금액과 순공정가치 중 낮은 값으로 측정하고 감가상각 중단.",
      diff="advanced",
      conf="ppe", cr="매각예정으로 재분류되면 감가상각 중단되고 평가 기준이 바뀜"),
    # ── 감가상각 / 무형자산 상각 (5) ──
    t("straight-line-depreciation", "정액법", "straight-line depreciation", "accounting", "financial_assets",
      "내용연수 동안 매기 동일한 금액을 감가상각비로 인식하는 방법.",
      formula="감가상각비 = (취득원가 - 잔존가치) / 내용연수",
      diff="foundational",
      conf="declining-balance-depreciation", cr="정액법은 매기 일정, 정률법은 초기 가속 상각"),
    t("declining-balance-depreciation", "정률법", "declining-balance depreciation", "accounting", "financial_assets",
      "기초 장부금액에 일정 상각률을 곱해 감가상각비를 산출하는 방법. 초기 부담이 크고 후기로 갈수록 감소.",
      formula="감가상각비 = 기초 장부금액 × 상각률",
      conf="straight-line-depreciation", cr="정률법은 가속상각, 정액법은 균등상각"),
    t("units-of-production", "생산량비례법", "units-of-production method", "accounting", "financial_assets",
      "실제 생산량(또는 사용량)에 비례해 감가상각비를 계산하는 방법. 자원 추출 자산에 적합.",
      formula="감가상각비 = (취득원가 - 잔존가치) × 당기 생산량 / 총 추정 생산량",
      conf="straight-line-depreciation", cr="생산량비례법은 조업도 연동, 정액법은 시간 기준"),
    t("capital-expenditure", "자본적 지출", "capital expenditure", "accounting", "financial_assets",
      "자산의 가치 증가나 내용연수 연장을 가져오는 지출. 자산의 장부금액에 가산되어 감가상각 대상이 된다.",
      conf="revenue-expenditure", cr="자본적 지출은 자산화, 수익적 지출은 즉시 비용"),
    t("revenue-expenditure", "수익적 지출", "revenue expenditure", "accounting", "financial_assets",
      "자산의 정상적 기능 유지를 위한 지출. 발생 시점에 비용으로 처리한다.",
      conf="capital-expenditure", cr="수익적 지출은 즉시 비용, 자본적 지출은 자산 추가"),
    # ── 부채 / 사채 (10) ──
    t("bond-at-par", "액면발행", "bond at par", "accounting", "financial_assets",
      "사채를 액면금액과 동일한 금액으로 발행하는 것. 발행시 시장이자율과 액면이자율이 같다.",
      diff="foundational",
      conf="bond-discount", cr="액면발행은 표면=시장이자율, 할인발행은 표면<시장이자율"),
    t("bond-discount", "할인발행", "bond at discount", "accounting", "financial_assets",
      "사채를 액면금액보다 낮은 금액으로 발행하는 것. 시장이자율이 액면이자율보다 높을 때 발생.",
      conf="bond-premium", cr="할인발행은 표면<시장, 할증발행은 표면>시장"),
    t("bond-premium", "할증발행", "bond at premium", "accounting", "financial_assets",
      "사채를 액면금액보다 높은 금액으로 발행하는 것. 시장이자율이 액면이자율보다 낮을 때 발생.",
      conf="bond-discount", cr="할증발행은 표면>시장, 할인발행은 표면<시장"),
    t("convertible-bond", "전환사채", "convertible bond", "accounting", "financial_assets",
      "보유자가 일정 기간 내에 발행회사 주식으로 전환할 수 있는 권리가 부여된 사채. 부채요소와 자본요소로 분리 인식.",
      aliases=["CB"], diff="advanced",
      conf="bond-with-warrant", cr="전환사채는 사채 자체가 주식으로 전환, 신주인수권부사채는 사채는 남고 신주 인수권만 행사"),
    t("bond-with-warrant", "신주인수권부사채", "bond with warrant", "accounting", "financial_assets",
      "사채에 신주인수권이 함께 부여된 사채. 인수권 행사 후에도 사채는 그대로 존속.",
      aliases=["BW"], diff="advanced",
      conf="convertible-bond", cr="BW는 신주인수권만 분리 행사, CB는 사채 자체가 주식으로 전환"),
    t("redemption-right", "조기상환권", "redemption right", "accounting", "financial_assets",
      "사채 발행자 또는 보유자가 만기 전 상환을 요구할 수 있는 권리. 내재파생상품으로 평가 대상이 될 수 있다.",
      diff="advanced",
      conf="convertible-bond", cr="조기상환권은 상환 요구 권리, 전환권은 주식 전환 요구 권리"),
    t("perpetual-bond", "영구사채", "perpetual bond", "accounting", "financial_assets",
      "만기가 없고 이자만 지급하는 사채. K-IFRS 분류상 자본 또는 부채로 갈라질 수 있다.",
      diff="advanced",
      conf="bond-at-par", cr="영구사채는 만기 없음, 일반사채는 만기 존재"),
    t("financial-guarantee", "금융보증계약", "financial guarantee contract", "accounting", "financial_assets",
      "특정 채무자가 채무를 이행하지 못할 때 보유자에게 손실을 보상하기로 한 계약. 최초 인식 시 공정가치로 측정.",
      diff="advanced",
      conf="provision", cr="금융보증은 계약상 의무, 충당부채는 현재의무 + 추정 가능 시 인식"),
    t("commercial-paper", "기업어음", "commercial paper", "accounting", "financial_assets",
      "단기 자금 조달 목적의 무담보 약속어음. 만기 1년 이내가 일반적이며 할인 발행.",
      aliases=["CP"], diff="foundational",
      conf="convertible-bond", cr="CP는 단기 무담보, CB는 장기 전환 옵션 포함"),
    t("debt-securities-classification", "채무증권 분류", "debt securities classification", "accounting", "financial_assets",
      "K-IFRS 1109호에서 채무상품 금융자산을 보유 목적·SPPI 조건에 따라 AC/FVOCI/FVPL로 분류하는 체계.",
      diff="advanced",
      conf="sppi-test", cr="분류 체계는 결과, SPPI는 분류 판단의 한 축(현금흐름 특성)"),
    # ── 자본 (10) ──
    t("share-capital", "자본금", "share capital", "accounting", "equity",
      "발행한 주식의 액면가액 합계. 회사 설립 또는 증자 시 증가하며 감자로 감소.",
      diff="foundational",
      conf="share-premium", cr="자본금은 액면가액 부분, 주식발행초과금은 액면 초과 발행분"),
    t("share-premium", "주식발행초과금", "share premium", "accounting", "equity",
      "주식을 액면가액보다 높은 가액으로 발행할 때 그 초과분. 자본잉여금에 속한다.",
      conf="share-capital", cr="주식발행초과금은 액면 초과분, 자본금은 액면가액 자체"),
    t("retained-earnings", "이익잉여금", "retained earnings", "accounting", "equity",
      "당기순이익 중 배당이나 적립으로 처분되지 않고 사내에 누적된 이익.",
      diff="foundational",
      conf="capital-surplus", cr="이익잉여금은 이익에서 발생, 자본잉여금은 자본거래에서 발생"),
    t("capital-surplus", "자본잉여금", "capital surplus", "accounting", "equity",
      "주식발행초과금, 감자차익, 자기주식처분이익 등 자본거래에서 발생한 잉여금. 결손보전 외에는 처분 제한.",
      conf="retained-earnings", cr="자본잉여금은 자본거래, 이익잉여금은 손익거래에서 발생"),
    t("treasury-stock", "자기주식", "treasury stock", "accounting", "equity",
      "회사가 발행한 주식을 자기가 다시 취득해 보유하는 것. 자본의 차감 항목으로 표시한다.",
      conf="share-buyback", cr="자기주식은 보유 상태, 자사주매입은 취득 거래"),
    t("share-buyback", "자사주매입", "share buyback", "accounting", "equity",
      "회사가 자기 발행 주식을 시장에서 다시 사들이는 거래. 결과로 자기주식이 발생한다.",
      conf="treasury-stock", cr="자사주매입은 거래(동사), 자기주식은 결과(명사)"),
    t("appropriation-of-retained-earnings", "이익잉여금 처분", "appropriation of retained earnings", "accounting", "equity",
      "이익잉여금을 배당, 법정적립금, 임의적립금 등으로 배분하는 절차. 주주총회 결의로 확정.",
      conf="dividend-payment", cr="처분은 전체 절차, 배당은 처분의 한 항목"),
    t("legal-reserve", "이익준비금", "legal reserve", "accounting", "equity",
      "상법상 매 결산기 금전배당의 10% 이상을 자본금의 50%에 달할 때까지 적립해야 하는 법정적립금.",
      conf="voluntary-reserve", cr="이익준비금은 상법상 강제, 임의적립금은 정관/주총 결의로 임의 적립"),
    t("voluntary-reserve", "임의적립금", "voluntary reserve", "accounting", "equity",
      "정관이나 주주총회 결의로 임의 적립한 이익잉여금 일부. 사용목적이 정해진 경우와 사용제한이 없는 경우 구분.",
      conf="legal-reserve", cr="임의적립금은 자율 적립, 이익준비금은 법정 강제"),
    t("other-comprehensive-income", "기타포괄손익", "other comprehensive income", "accounting", "equity",
      "당기순이익에 포함되지 않고 자본으로 직접 인식되는 손익. 재평가잉여금, FVOCI 평가손익 등.",
      aliases=["OCI"], diff="intermediate",
      conf="profit-or-loss", cr="OCI는 자본 변동, 당기손익은 P/L 반영"),
    # ── 수익인식 추가 (10) ──
    t("percentage-of-completion", "진행기준", "percentage of completion method", "accounting", "revenue",
      "장기 계약 등에서 수행 진행률에 따라 매출과 원가를 비례 인식하는 방법.",
      formula="진행률 = 누적 발생원가 / 추정 총원가",
      conf="completed-contract", cr="진행기준은 기간 안분, 완성기준은 완성 시 한꺼번에"),
    t("completed-contract", "완성기준", "completed-contract method", "accounting", "revenue",
      "계약 완료 시점에 매출을 일괄 인식하는 방법. K-IFRS 1115호에서는 일반적으로 인정되지 않는다.",
      conf="percentage-of-completion", cr="완성기준은 일시 인식, 진행기준은 기간 안분"),
    t("consignment-sale", "위탁판매", "consignment sale", "accounting", "revenue",
      "수탁자가 위탁자의 재화를 보관·판매하고 수수료를 받는 거래. 위탁자는 수탁자의 판매 시점에 매출 인식.",
      conf="installment-sale", cr="위탁판매는 제3자 판매, 할부판매는 분할 회수 조건"),
    t("installment-sale", "할부판매", "installment sale", "accounting", "revenue",
      "재화 인도 후 대금을 분할 회수하는 판매 형태. 수익은 인도 시점에 인식, 매출채권의 현재가치로 측정.",
      conf="consignment-sale", cr="할부판매는 회수조건, 위탁판매는 판매주체"),
    t("bill-and-hold", "미인도 청구판매", "bill-and-hold arrangement", "accounting", "revenue",
      "고객이 대금을 지급하고 소유권을 가지지만 인도는 나중에 받기로 한 거래. 일정 요건 충족 시 매출 인식 가능.",
      diff="advanced",
      conf="contract-asset", cr="미인도 청구는 인도 지연 케이스, 계약자산은 청구 미발생 케이스"),
    t("variable-consideration", "변동대가", "variable consideration", "accounting", "revenue",
      "할인, 리베이트, 환불, 인센티브 등으로 거래가격이 변동되는 부분. 기대값 또는 가장 가능성 높은 값으로 추정.",
      diff="advanced",
      conf="performance-obligation", cr="변동대가는 거래가격 산정 이슈, 수행의무는 인식 단위 이슈"),
    t("principal-vs-agent", "본인 vs 대리인", "principal vs agent", "accounting", "revenue",
      "재화/용역 통제 여부에 따라 본인(총액 매출)이냐 대리인(순액 매출)이냐를 판단하는 기준.",
      diff="advanced",
      conf="consignment-sale", cr="본인/대리인 판단은 매출 표시 방법, 위탁판매는 본인/대리인 판단의 한 케이스"),
    t("significant-financing-component", "유의적 금융요소", "significant financing component", "accounting", "revenue",
      "계약대금 수령 시기와 재화 인도 시기 차이가 1년을 초과해 사실상 자금 제공 요소가 포함된 거래. 이자수익을 별도 인식.",
      diff="advanced",
      conf="installment-sale", cr="유의적 금융요소는 시점 차이가 1년 초과한 케이스 일반, 할부판매는 그 한 예"),
    t("return-allowance", "환불충당부채", "refund liability", "accounting", "revenue",
      "고객 반품 권리로 인해 매출이 줄어들 가능성에 대비해 인식하는 부채. 매출 인식 시점에 추정 반품률로 측정.",
      conf="provision", cr="환불충당부채는 매출 관련, 일반 충당부채는 비용/소송 등"),
    t("warranty-cost", "제품보증비", "warranty cost", "accounting", "revenue",
      "판매한 제품에 대한 보증 의무로 인해 인식하는 비용. 통상 충당부채로 계상.",
      conf="provision", cr="제품보증비는 비용, 충당부채는 그에 대응하는 부채"),
    # ── 종업원급여/리스/관계기업 (8) ──
    t("defined-contribution", "확정기여형 퇴직급여", "defined contribution plan", "accounting", "employee_benefits",
      "기업이 매기 기여금만 납부하면 책임이 종료되는 제도. 미래 지급액 위험은 종업원이 부담.",
      aliases=["DC"], diff="intermediate",
      conf="defined-benefit-obligation", cr="DC는 매기 기여금 납부로 종결, DB는 미래 지급액에 대한 책임"),
    t("plan-assets", "사외적립자산", "plan assets", "accounting", "employee_benefits",
      "확정급여제도를 위해 외부에 적립한 자산. 확정급여채무를 차감해 순부채/순자산을 산출.",
      diff="advanced",
      conf="defined-benefit-obligation", cr="사외적립자산은 자산 측, DBO는 부채 측"),
    t("actuarial-gain-loss", "보험수리적손익", "actuarial gain/loss", "accounting", "employee_benefits",
      "확정급여채무 측정 가정 변화로 발생한 손익. 기타포괄손익으로 인식하고 재분류되지 않는다.",
      diff="advanced",
      conf="defined-benefit-obligation", cr="보험수리적손익은 DBO 측정 변동, DBO는 부채 자체"),
    t("operating-lease", "운용리스", "operating lease", "accounting", "leases",
      "K-IFRS 1116 시행 이후 리스이용자 입장에서는 사용권자산/리스부채 인식 원칙이 같지만, 리스제공자에게는 기존 분류 의미가 남아있는 리스 유형.",
      diff="intermediate",
      conf="finance-lease", cr="운용리스는 위험·보상 미이전, 금융리스는 위험·보상 이전"),
    t("finance-lease", "금융리스", "finance lease", "accounting", "leases",
      "리스자산의 위험과 보상의 대부분이 리스이용자에게 이전된 리스. 리스제공자는 리스채권 인식.",
      conf="operating-lease", cr="금융리스는 위험/보상 이전, 운용리스는 미이전"),
    t("short-term-lease", "단기리스", "short-term lease", "accounting", "leases",
      "리스기간 12개월 이하 리스. 리스이용자가 사용권자산/리스부채 인식 면제 선택 가능.",
      conf="finance-lease", cr="단기리스는 12개월 이하 면제 가능, 금융리스는 기간/조건과 무관한 분류"),
    t("non-controlling-interest", "비지배지분", "non-controlling interest", "accounting", "business_combination",
      "지배기업 외의 주주가 종속기업에 보유한 지분. 연결재무제표 자본 항목에 별도 표시.",
      aliases=["NCI"], diff="advanced",
      conf="consolidation", cr="비지배지분은 항목, 연결재무제표는 그 항목을 표시하는 보고체계"),
    t("joint-venture", "공동기업", "joint venture", "accounting", "business_combination",
      "두 당사자 이상이 공동 지배하면서 순자산에 대한 권리를 보유하는 약정. 지분법 적용.",
      diff="advanced",
      conf="equity-method", cr="공동기업은 대상, 지분법은 적용 방법"),
    # ── 회계정책/오류/외화 (5) ──
    t("change-in-accounting-policy", "회계정책 변경", "change in accounting policy", "accounting", "financial_assets",
      "회계기준 변경 등으로 회계정책을 바꾸는 것. 원칙적으로 소급 적용한다.",
      diff="advanced",
      conf="change-in-accounting-estimate", cr="정책 변경은 소급, 추정 변경은 전진"),
    t("change-in-accounting-estimate", "회계추정 변경", "change in accounting estimate", "accounting", "financial_assets",
      "추정의 기초 정보 변경으로 회계추정을 바꾸는 것. 전진적으로 적용한다.",
      diff="advanced",
      conf="change-in-accounting-policy", cr="추정 변경은 전진, 정책 변경은 소급"),
    t("prior-period-error", "전기오류수정", "prior period error correction", "accounting", "financial_assets",
      "중대한 전기 회계오류를 발견 시 소급해 재무제표를 재작성하는 절차.",
      diff="advanced",
      conf="change-in-accounting-policy", cr="오류수정과 정책변경 모두 소급이지만, 사유가 다름(오류 vs 기준 변경)"),
    t("functional-currency", "기능통화", "functional currency", "accounting", "financial_assets",
      "기업의 주된 영업환경에서 사용하는 통화. 외화환산의 기준이 된다.",
      diff="advanced",
      conf="presentation-currency", cr="기능통화는 영업환경 기준, 표시통화는 재무제표 작성 통화"),
    t("presentation-currency", "표시통화", "presentation currency", "accounting", "financial_assets",
      "재무제표를 표시하는 통화. 기능통화와 다를 수 있으며 환산 절차가 필요하다.",
      diff="advanced",
      conf="functional-currency", cr="표시통화는 보고 통화, 기능통화는 영업 통화"),
    # ── 위험회피 / 기타 (8) ──
    t("hedge-accounting", "위험회피회계", "hedge accounting", "accounting", "financial_assets",
      "위험회피 도구와 위험회피 대상의 손익을 같은 기간에 인식하기 위한 특수회계. 적용 요건 충족 시 선택.",
      diff="advanced",
      conf="fair-value-hedge", cr="위험회피회계는 우산 개념, 공정가치/현금흐름 위험회피는 세부 유형"),
    t("fair-value-hedge", "공정가치위험회피", "fair value hedge", "accounting", "financial_assets",
      "공정가치 변동 위험을 회피하기 위한 위험회피. 회피대상과 도구의 평가손익을 모두 당기손익에 인식.",
      diff="advanced",
      conf="cash-flow-hedge", cr="공정가치 위험회피는 P/L 즉시 인식, 현금흐름 위험회피는 OCI 후 재분류"),
    t("cash-flow-hedge", "현금흐름위험회피", "cash flow hedge", "accounting", "financial_assets",
      "미래 현금흐름 변동 위험을 회피. 도구 손익 중 효과적인 부분은 OCI로, 비효과적인 부분은 당기손익으로.",
      diff="advanced",
      conf="fair-value-hedge", cr="현금흐름 위험회피는 OCI 경유, 공정가치 위험회피는 즉시 P/L"),
    t("derivative", "파생상품", "derivative", "accounting", "financial_assets",
      "기초변수 변동에 따라 가치가 변하고, 최초 순투자액이 작거나 없으며, 미래 결제되는 금융상품. 원칙적으로 FVPL 측정.",
      diff="intermediate",
      conf="embedded-derivative", cr="파생상품은 독립 계약, 내재파생상품은 다른 계약 안에 포함"),
    t("embedded-derivative", "내재파생상품", "embedded derivative", "accounting", "financial_assets",
      "주계약 안에 포함된 파생상품 요소. 일정 요건 충족 시 주계약과 분리해 별도 평가.",
      diff="advanced",
      conf="derivative", cr="내재파생은 주계약 일부, 파생상품은 독립 계약"),
    t("ifrs-vs-kgaap", "K-IFRS vs 일반기업회계기준", "K-IFRS vs K-GAAP", "accounting", "financial_assets",
      "상장기업은 K-IFRS 의무 적용, 비상장 중소기업은 일반기업회계기준 적용 가능. 둘은 측정/공시에서 차이가 있다.",
      conf="amortized-cost", cr="K-IFRS와 K-GAAP은 기준 체계 자체, 상각후원가는 두 체계 모두에서 사용되는 측정기준"),
    t("subsequent-event", "후속사건", "subsequent event", "accounting", "financial_assets",
      "보고기간 말 이후 재무제표 발행승인일까지 발생한 사건. 수정을 요하는 사건과 수정을 요하지 않는 사건으로 구분.",
      conf="prior-period-error", cr="후속사건은 보고기간 말 이후 사건, 전기오류수정은 과거 오류 수정"),
    t("related-party", "특수관계자", "related party", "accounting", "financial_assets",
      "재무·영업 의사결정에 영향을 미치거나 받는 자. 거래 내용을 주석에 공시해야 한다.",
      conf="business-combination", cr="특수관계자는 관계 자체, 사업결합은 그 관계로부터 발생할 수 있는 거래 중 하나"),
    # ── 원가관리 (+10) ──
    t("job-order-costing", "개별원가계산", "job-order costing", "accounting", "cost_management",
      "주문/작업별로 원가를 집계하는 방식. 다품종 소량 생산이나 수주 생산에 적합.",
      conf="process-costing", cr="개별원가는 주문 단위 집계, 종합원가는 공정 단위 흐름"),
    t("normal-costing", "정상원가계산", "normal costing", "accounting", "cost_management",
      "직접재료비/직접노무비는 실제, 제조간접비는 예정배부율로 적용하는 방식.",
      conf="standard-cost", cr="정상원가는 간접비만 예정, 표준원가는 모든 원가요소를 사전 표준"),
    t("predetermined-overhead-rate", "예정배부율", "predetermined overhead rate", "accounting", "cost_management",
      "기초 추정 제조간접비를 기준조업도로 나눈 비율. 정상원가계산에서 사용.",
      formula="예정배부율 = 추정 제조간접비 / 추정 기준조업도",
      conf="normal-costing", cr="예정배부율은 비율, 정상원가는 그 비율을 사용하는 방법"),
    t("direct-labor", "직접노무비", "direct labor", "accounting", "cost_management",
      "특정 제품 생산에 직접 투입된 노무비. 원가 추적이 가능한 인건비.",
      diff="foundational",
      conf="indirect-cost", cr="직접노무비는 추적 가능, 간접노무비는 배부 필요"),
    t("manufacturing-overhead", "제조간접비", "manufacturing overhead", "accounting", "cost_management",
      "직접재료비/직접노무비를 제외한 모든 제조원가. 배부 기준이 필요하다.",
      diff="foundational",
      conf="direct-labor", cr="제조간접비는 배부 대상, 직접노무비는 직접 추적"),
    t("indirect-cost", "간접비", "indirect cost", "accounting", "cost_management",
      "특정 원가대상에 직접 추적할 수 없어 배부가 필요한 원가.",
      diff="foundational",
      conf="manufacturing-overhead", cr="간접비는 일반 개념, 제조간접비는 제조에 한정된 간접비"),
    t("direct-allocation-method", "직접배부법", "direct allocation method", "accounting", "cost_management",
      "보조부문 원가를 보조부문 간 용역 수수 무시하고 제조부문에만 배부하는 가장 단순한 방법.",
      conf="step-method", cr="직접배부법은 보조→제조만, 단계배부법은 보조→일부 보조→제조"),
    t("step-method", "단계배부법", "step allocation method", "accounting", "cost_management",
      "보조부문 원가를 일정 순서로 다른 보조부문에 일부 배부 후 제조부문에 배부. 단방향 흐름.",
      conf="reciprocal-method", cr="단계배부는 단방향, 상호배부는 양방향(연립방정식)"),
    t("reciprocal-method", "상호배부법", "reciprocal allocation method", "accounting", "cost_management",
      "보조부문 간 상호 용역 수수를 연립방정식으로 완전히 반영해 배부하는 방법.",
      diff="advanced",
      conf="step-method", cr="상호배부는 연립방정식 풀이, 단계배부는 순서 결정 후 단방향"),
    t("conversion-cost", "가공원가", "conversion cost", "accounting", "cost_management",
      "직접재료비를 제외한 직접노무비와 제조간접비의 합. 종합원가계산에서 완성품환산량 산출의 기초.",
      formula="가공원가 = 직접노무비 + 제조간접비",
      conf="direct-labor", cr="가공원가는 노무+간접의 합, 직접노무비는 그 한 구성요소"),
    # ═══════════════════ business (+80) ═══════════════════
    # ── 재무관리 (+50) ──
    t("efficient-market-hypothesis", "효율적 시장 가설", "efficient market hypothesis", "business", "financial_management",
      "시장 가격이 이용 가능한 정보를 모두 반영한다는 가설. 약형/준강형/강형으로 구분.",
      aliases=["EMH"], diff="intermediate",
      conf="random-walk", cr="EMH는 효율성에 대한 이론, 랜덤워크는 그 결과로 나타나는 가격 행태"),
    t("random-walk", "랜덤워크", "random walk", "business", "financial_management",
      "주가 변동이 과거 변동과 독립적이라는 가설. EMH 약형의 통계적 표현.",
      conf="efficient-market-hypothesis", cr="랜덤워크는 통계적 성질, EMH는 그 배경 이론"),
    t("per", "주가수익비율", "price-to-earnings ratio", "business", "financial_management",
      "주가를 주당순이익으로 나눈 비율. 시장이 이익에 매기는 배수.",
      aliases=["PER", "P/E"],
      formula="PER = 주가 / EPS",
      conf="pbr", cr="PER는 이익 기준 배수, PBR는 순자산 기준 배수"),
    t("pbr", "주가순자산비율", "price-to-book ratio", "business", "financial_management",
      "주가를 주당순자산으로 나눈 비율. 청산가치 대비 시장가치.",
      aliases=["PBR", "P/B"],
      formula="PBR = 주가 / BPS",
      conf="per", cr="PBR는 자본 기준, PER는 이익 기준"),
    t("psr", "주가매출액비율", "price-to-sales ratio", "business", "financial_management",
      "주가를 주당매출액으로 나눈 비율. 적자 기업 평가에 유용.",
      aliases=["PSR"],
      conf="per", cr="PSR는 매출 기준, PER는 이익 기준"),
    t("ev-ebitda", "EV/EBITDA", "enterprise value to EBITDA", "business", "financial_management",
      "기업가치를 영업현금흐름 근사치(EBITDA)로 나눈 비율. 자본구조와 무관한 비교 가능.",
      diff="advanced",
      conf="per", cr="EV/EBITDA는 자본구조 중립, PER는 자기자본 기준"),
    t("arbitrage", "차익거래", "arbitrage", "business", "financial_management",
      "위험 없이 무비용으로 이익을 얻는 거래. 효율적 시장에서는 즉시 소멸된다.",
      conf="efficient-market-hypothesis", cr="차익거래 부재는 EMH의 강한 형태 결과"),
    t("put-call-parity", "풋콜패리티", "put-call parity", "business", "financial_management",
      "동일 기초자산/만기/행사가의 콜과 풋 옵션 가격 관계식. 차익거래 부재 조건에서 성립.",
      formula="C - P = S - K/(1+r)^T",
      diff="advanced",
      conf="black-scholes", cr="풋콜패리티는 항등식, 블랙숄즈는 가격 모델"),
    t("black-scholes", "블랙숄즈 모형", "Black-Scholes model", "business", "financial_management",
      "유럽형 옵션 가격을 정규분포 가정에서 산출하는 폐쇄형 공식.",
      diff="advanced",
      conf="put-call-parity", cr="블랙숄즈는 모델 가정 필요, 풋콜패리티는 모델 무관 항등식"),
    t("ytm", "만기수익률", "yield to maturity", "business", "financial_management",
      "채권을 만기까지 보유했을 때 얻을 수 있는 평균 수익률. 시장가격을 미래 현금흐름의 현재가치와 일치시키는 할인율.",
      aliases=["YTM"], diff="intermediate",
      conf="coupon-rate", cr="YTM은 시장 평가, 표면이자율은 발행 시 명시"),
    t("coupon-rate", "표면이자율", "coupon rate", "business", "financial_management",
      "사채의 액면금액에 대해 매기 지급하는 이자율. 발행 시 정해지며 변하지 않는다.",
      conf="ytm", cr="표면이자율은 액면 기준 고정, YTM은 시장가 기준 변동"),
    t("nominal-interest-rate", "액면이자율", "nominal interest rate", "business", "financial_management",
      "현금 수취액 기준의 이자율. 사채의 표면이자율과 같은 의미로 쓰인다.",
      conf="effective-interest-rate", cr="액면이자율은 표면값, 유효이자율은 시장이 평가한 실질 수익률"),
    t("market-portfolio", "시장포트폴리오", "market portfolio", "business", "financial_management",
      "시가총액 가중 평균으로 모든 위험자산을 포함한 포트폴리오. CAPM에서 베타 1의 기준.",
      conf="efficient-frontier", cr="시장포트폴리오는 한 점, 효율적 프론티어는 위험-수익 효율 곡선"),
    t("efficient-frontier", "효율적 프론티어", "efficient frontier", "business", "financial_management",
      "주어진 위험에서 기대수익률을 최대화한 포트폴리오들의 집합. 마코위츠 분산투자 이론의 핵심.",
      diff="advanced",
      conf="cml", cr="효율적 프론티어는 위험자산만, CML은 무위험자산 결합 후 직선"),
    t("cml", "자본시장선", "capital market line", "business", "financial_management",
      "무위험자산과 시장포트폴리오를 결합한 포트폴리오의 위험-수익 관계 직선.",
      aliases=["CML"], diff="advanced",
      conf="sml", cr="CML은 효율적 포트폴리오(총위험), SML은 개별자산(체계적 위험)"),
    t("sml", "증권시장선", "security market line", "business", "financial_management",
      "CAPM에서 베타와 기대수익률의 관계 직선. 개별 자산의 적정 수익률을 보여준다.",
      aliases=["SML"], diff="advanced",
      conf="cml", cr="SML은 베타-수익률, CML은 총위험-수익률"),
    t("sharpe-ratio", "샤프지수", "Sharpe ratio", "business", "financial_management",
      "초과수익을 총위험(표준편차)으로 나눈 비율. 포트폴리오 위험 조정 성과 지표.",
      formula="Sharpe = (Rp - Rf) / σp",
      conf="treynor-ratio", cr="샤프는 총위험 분모, 트레이너는 체계적 위험(베타) 분모"),
    t("treynor-ratio", "트레이너지수", "Treynor ratio", "business", "financial_management",
      "초과수익을 베타로 나눈 비율. 체계적 위험 기준 성과 지표.",
      formula="Treynor = (Rp - Rf) / βp",
      conf="sharpe-ratio", cr="트레이너는 베타 분모, 샤프는 표준편차 분모"),
    t("jensen-alpha", "젠센 알파", "Jensen's alpha", "business", "financial_management",
      "실현 수익률과 CAPM 예측 수익률의 차이. 양수면 초과성과, 음수면 미달성과.",
      formula="α = Rp - [Rf + βp(Rm - Rf)]",
      diff="advanced",
      conf="sharpe-ratio", cr="알파는 절대 초과수익, 샤프는 위험단위당 초과수익"),
    t("operating-leverage", "영업레버리지", "operating leverage", "business", "financial_management",
      "고정영업비용 비중으로 인해 매출 변동이 영업이익에 증폭되는 정도.",
      formula="DOL = 공헌이익 / 영업이익",
      conf="financial-leverage", cr="영업레버리지는 고정영업비, 재무레버리지는 고정금융비"),
    t("financial-leverage", "재무레버리지", "financial leverage", "business", "financial_management",
      "고정금융비용(이자) 비중으로 인해 영업이익 변동이 EPS에 증폭되는 정도.",
      formula="DFL = 영업이익 / (영업이익 - 이자)",
      conf="operating-leverage", cr="재무레버리지는 이자 영향, 영업레버리지는 고정영업비 영향"),
    t("combined-leverage", "결합레버리지", "combined leverage", "business", "financial_management",
      "영업레버리지와 재무레버리지를 곱한 값. 매출 변동이 EPS에 미치는 총 증폭효과.",
      formula="DCL = DOL × DFL",
      conf="operating-leverage", cr="결합은 곱, 영업/재무는 그 구성요소"),
    t("residual-dividend", "잔여배당정책", "residual dividend policy", "business", "financial_management",
      "투자안에 우선 자금을 사용하고 남은 부분만 배당하는 정책.",
      conf="stable-dividend", cr="잔여배당은 변동성 큰 배당, 안정배당은 일정 수준 유지"),
    t("stable-dividend", "안정배당정책", "stable dividend policy", "business", "financial_management",
      "이익 변동과 무관하게 일정 수준의 배당을 지속하려는 정책.",
      conf="residual-dividend", cr="안정배당은 평탄화, 잔여배당은 투자 후 잔여만"),
    t("bird-in-hand", "수중의 새 이론", "bird-in-the-hand theory", "business", "financial_management",
      "투자자가 미래 자본이득보다 현재의 확실한 배당을 선호한다는 이론. 고배당주가 선호됨을 시사.",
      diff="advanced",
      conf="mm-proposition", cr="MM은 배당 무관 가정, 수중의 새 이론은 배당이 가치에 영향"),
    t("clientele-effect", "고객효과", "clientele effect", "business", "financial_management",
      "투자자 유형(세금, 선호)에 따라 특정 배당정책을 가진 기업이 선호된다는 효과.",
      diff="advanced",
      conf="bird-in-hand", cr="고객효과는 투자자 그룹 분화, 수중의 새 이론은 일반적 선호"),
    t("share-split", "주식분할", "stock split", "business", "financial_management",
      "1주를 여러 주로 쪼개 발행주식수를 늘리고 액면가를 낮추는 행위. 자본금 총액 불변.",
      conf="bonus-issue", cr="주식분할은 액면가 감소, 무상증자는 자본금 증가"),
    t("bonus-issue", "무상증자", "bonus issue", "business", "financial_management",
      "이익잉여금 등 잉여금을 자본금으로 전입해 주식을 무상으로 신주발행하는 것.",
      conf="share-split", cr="무상증자는 자본금 증가, 주식분할은 액면가 감소만"),
    t("rights-issue", "유상증자", "rights issue", "business", "financial_management",
      "현금 납입을 받고 신주를 발행하는 자본 조달 방식.",
      conf="bonus-issue", cr="유상증자는 현금 납입, 무상증자는 잉여금 자본전입"),
    t("forward-contract", "선도계약", "forward contract", "business", "financial_management",
      "미래 특정 시점에 정해진 가격으로 매매를 약정한 장외 파생상품.",
      conf="futures-contract", cr="선도는 장외, 선물은 거래소 표준화"),
    t("futures-contract", "선물계약", "futures contract", "business", "financial_management",
      "거래소 표준 계약으로 미래에 정해진 가격으로 매매를 약정한 파생상품. 일일정산과 증거금 제도.",
      conf="forward-contract", cr="선물은 거래소 + 일일정산, 선도는 장외 + 만기일 정산"),
    t("swap", "스왑", "swap", "business", "financial_management",
      "두 당사자가 일정 기간 현금흐름을 교환하기로 약정하는 파생상품. 이자율 스왑, 통화 스왑 등.",
      conf="forward-contract", cr="스왑은 연속 교환, 선도는 단일 시점 교환"),
    t("call-option", "콜옵션", "call option", "business", "financial_management",
      "기초자산을 정해진 행사가격에 살 수 있는 권리. 매수자는 권리만, 매도자는 의무.",
      diff="intermediate",
      conf="put-option", cr="콜은 매수 권리, 풋은 매도 권리"),
    t("put-option", "풋옵션", "put option", "business", "financial_management",
      "기초자산을 정해진 행사가격에 팔 수 있는 권리.",
      conf="call-option", cr="풋은 매도 권리, 콜은 매수 권리"),
    t("american-option", "미국식 옵션", "American option", "business", "financial_management",
      "만기 전 언제든 행사할 수 있는 옵션.",
      conf="european-option", cr="미국식은 언제든, 유럽식은 만기에만"),
    t("european-option", "유럽식 옵션", "European option", "business", "financial_management",
      "만기일에만 행사할 수 있는 옵션. 블랙숄즈 모형의 표준 가정.",
      conf="american-option", cr="유럽식은 만기에만, 미국식은 언제든"),
    t("intrinsic-value", "내재가치", "intrinsic value", "business", "financial_management",
      "옵션이 즉시 행사될 때의 가치. 콜은 max(S-K, 0), 풋은 max(K-S, 0).",
      conf="time-value", cr="내재가치는 즉시 행사 가치, 시간가치는 만기까지 남은 가치 변동 잠재력"),
    t("time-value", "시간가치(옵션)", "option time value", "business", "financial_management",
      "옵션 프리미엄에서 내재가치를 뺀 나머지. 만기까지 가치 변동 가능성을 반영.",
      conf="intrinsic-value", cr="시간가치는 추가 가능성, 내재가치는 현재 행사 시 가치"),
    t("in-the-money", "내가격", "in the money", "business", "financial_management",
      "내재가치가 양인 옵션 상태.",
      aliases=["ITM"],
      conf="out-of-the-money", cr="ITM은 내재가치>0, OTM은 내재가치=0"),
    t("out-of-the-money", "외가격", "out of the money", "business", "financial_management",
      "내재가치가 0인 옵션 상태. 시간가치만 존재.",
      aliases=["OTM"],
      conf="in-the-money", cr="OTM은 즉시 행사 가치 없음, ITM은 있음"),
    t("operating-cash-flow", "영업현금흐름", "operating cash flow", "business", "financial_management",
      "기업의 본업에서 발생한 현금 유출입. 직접법과 간접법으로 산출.",
      diff="foundational",
      conf="free-cash-flow", cr="영업현금흐름은 본업 단계, FCF는 자본지출 차감 후 잔여"),
    t("free-cash-flow", "잉여현금흐름", "free cash flow", "business", "financial_management",
      "영업현금흐름에서 자본적 지출을 차감한 후 주주와 채권자에게 분배 가능한 현금.",
      aliases=["FCF"],
      formula="FCF = 영업CF - CapEx",
      conf="operating-cash-flow", cr="FCF는 분배 가능, 영업CF는 그 직전 단계"),
    t("equity-financing", "자기자본 조달", "equity financing", "business", "financial_management",
      "주식 발행이나 이익유보로 자금을 조달하는 방식.",
      diff="foundational",
      conf="debt-financing", cr="자기자본은 주주 자금, 타인자본은 채권자 자금"),
    t("debt-financing", "타인자본 조달", "debt financing", "business", "financial_management",
      "사채 발행, 차입금 등으로 자금을 조달하는 방식. 이자비용은 손금/필요경비 인정.",
      conf="equity-financing", cr="타인자본은 이자비용으로 절세효과, 자기자본은 배당으로 무절세"),
    t("merger-synergy", "합병시너지", "merger synergy", "business", "financial_management",
      "합병으로 결합된 기업가치가 단순 합보다 큰 차이. 영업/재무/세무 시너지로 구분.",
      conf="corporate-reorganization", cr="합병시너지는 결과, 합병/분할은 거래 자체"),
    t("merger-ratio", "합병비율", "merger ratio", "business", "financial_management",
      "합병 시 피합병회사 주주에게 발행할 신주 수를 결정하는 비율. 양사 주가 또는 가치에 근거.",
      conf="merger-synergy", cr="합병비율은 주식 배분, 합병시너지는 가치 증대"),
    t("tobins-q", "토빈의 Q", "Tobin's Q", "business", "financial_management",
      "기업 시장가치를 자산 대체원가로 나눈 비율. 투자 결정의 시그널로 사용.",
      formula="Q = 시장가치 / 대체원가",
      diff="advanced",
      conf="pbr", cr="토빈의 Q는 대체원가 기준, PBR는 장부가 기준"),
    t("agency-cost", "대리비용", "agency cost", "business", "financial_management",
      "주주와 경영자, 채권자와 주주 사이의 이해상충에서 발생하는 비용.",
      diff="advanced",
      conf="mm-proposition", cr="대리비용은 자본구조 결정 요인, MM은 그 요인을 무시한 가정"),
    t("pecking-order-theory", "자본조달 순위이론", "pecking order theory", "business", "financial_management",
      "기업이 내부유보 → 부채 → 신주발행 순으로 자금 조달을 선호한다는 이론.",
      diff="advanced",
      conf="trade-off-theory", cr="순위이론은 정보비대칭 기반, 상충이론은 절세-파산비용 trade-off"),
    t("modigliani-miller-with-tax", "MM 명제(법인세 포함)", "MM with corporate tax", "business", "financial_management",
      "법인세가 있을 때 이자비용 절세효과로 부채 사용이 기업가치를 증가시킨다는 MM의 수정 명제.",
      formula="V_L = V_U + t × D",
      diff="advanced",
      conf="mm-proposition", cr="세금 포함 MM은 부채 사용 권장, 무세 MM은 자본구조 무관"),
    t("real-option", "실물옵션", "real option", "business", "financial_management",
      "실물 투자 의사결정에 옵션 평가 기법을 적용한 분석. 확장/연기/포기 옵션 등.",
      diff="advanced",
      conf="call-option", cr="실물옵션은 실물 투자에 옵션 가치 적용, 콜옵션은 금융 파생상품"),
    t("capm-vs-apt", "CAPM vs APT", "CAPM vs APT", "business", "financial_management",
      "CAPM은 시장 베타 단일 요인, APT(차익가격결정이론)는 여러 거시 요인으로 수익률을 설명.",
      diff="advanced",
      conf="capm", cr="APT는 다요인 모델, CAPM은 단일요인(시장베타) 모델"),
    t("portfolio-variance", "포트폴리오 분산", "portfolio variance", "business", "financial_management",
      "포트폴리오 전체 위험의 분산. 개별자산 분산과 상관관계의 함수.",
      formula="σ_p² = Σ wi²σi² + 2Σ wiwj·Cov(i,j)",
      diff="advanced",
      conf="systematic-risk", cr="포트폴리오 분산은 총위험, 체계적 위험은 분산 불가능한 부분"),
    # ── 일반경영 (+30) ──
    t("stp-marketing", "STP 전략", "STP strategy", "business", "management_strategy",
      "Segmentation(시장 세분화) → Targeting(목표 시장 선정) → Positioning(포지셔닝)의 마케팅 전략 프레임.",
      diff="foundational",
      conf="marketing-mix", cr="STP는 시장 분석/선정, 4P는 실행 도구"),
    t("marketing-mix", "마케팅 믹스", "marketing mix", "business", "management_strategy",
      "Product, Price, Place, Promotion의 4P로 구성된 마케팅 실행 도구 조합.",
      aliases=["4P"], diff="foundational",
      conf="stp-marketing", cr="4P는 실행 변수, STP는 전략 수립"),
    t("product-life-cycle", "제품수명주기", "product life cycle", "business", "management_strategy",
      "도입기 → 성장기 → 성숙기 → 쇠퇴기로 이어지는 제품의 시장 단계.",
      aliases=["PLC"],
      conf="bcg-matrix", cr="PLC는 시간축 분석, BCG는 한 시점의 사업 포지셔닝"),
    t("bcg-matrix", "BCG 매트릭스", "BCG matrix", "business", "management_strategy",
      "시장 성장률과 상대적 시장점유율로 사업단위를 Star/Cash Cow/Question/Dog으로 분류.",
      conf="product-life-cycle", cr="BCG는 사업 포트폴리오, PLC는 단일 제품 단계"),
    t("ge-mckinsey", "GE-McKinsey 매트릭스", "GE-McKinsey matrix", "business", "management_strategy",
      "산업 매력도와 사업 강점으로 9칸 매트릭스에 사업을 배치. BCG보다 다차원.",
      conf="bcg-matrix", cr="GE-McKinsey는 9칸 다차원, BCG는 4칸 단순화"),
    t("blue-ocean", "블루오션 전략", "blue ocean strategy", "business", "management_strategy",
      "경쟁이 없는 새로운 시장 공간을 창출해 가치 혁신과 비용 절감을 동시 추구하는 전략.",
      conf="porters-five-forces", cr="블루오션은 경쟁 회피, 5 forces는 경쟁 분석"),
    t("core-competence", "핵심역량", "core competence", "business", "management_strategy",
      "경쟁사가 모방하기 어렵고 다양한 사업으로 확장 가능한 기업의 고유 능력.",
      conf="value-chain", cr="핵심역량은 능력, 가치사슬은 그 능력이 발현되는 활동"),
    t("differentiation", "차별화 전략", "differentiation strategy", "business", "management_strategy",
      "제품/서비스의 독특한 가치를 강조해 고가 프리미엄을 받는 전략. 포터의 3대 본원전략 중 하나.",
      conf="cost-leadership", cr="차별화는 독특함, 원가우위는 저원가"),
    t("cost-leadership", "원가우위 전략", "cost leadership strategy", "business", "management_strategy",
      "산업 내 최저원가 달성을 통해 경쟁우위를 확보하는 전략.",
      conf="differentiation", cr="원가우위는 가격경쟁, 차별화는 가치경쟁"),
    t("focus-strategy", "집중화 전략", "focus strategy", "business", "management_strategy",
      "특정 세분시장에 자원을 집중해 차별화 또는 원가우위를 달성.",
      conf="differentiation", cr="집중화는 좁은 시장, 차별화는 전체 시장 대상"),
    t("vertical-integration", "수직적 통합", "vertical integration", "business", "management_strategy",
      "원재료 공급(전방) 또는 유통(후방) 단계를 자체 운영하는 통합 전략.",
      conf="horizontal-integration", cr="수직적은 가치사슬 상하, 수평적은 동일 단계 확장"),
    t("horizontal-integration", "수평적 통합", "horizontal integration", "business", "management_strategy",
      "동일 사업 단계의 경쟁사 인수나 합병을 통한 확장.",
      conf="vertical-integration", cr="수평적은 동일 단계 합치기, 수직적은 상하 단계로 확장"),
    t("maslow-hierarchy", "매슬로 욕구위계", "Maslow's hierarchy", "business", "management_strategy",
      "생리적 → 안전 → 사회적 → 존중 → 자아실현의 5단계 욕구 위계 이론.",
      diff="foundational",
      conf="herzberg-two-factor", cr="매슬로는 위계적 욕구, 허즈버그는 동기-위생 2요인"),
    t("herzberg-two-factor", "허즈버그 2요인이론", "Herzberg's two-factor theory", "business", "management_strategy",
      "동기요인(성취/인정)과 위생요인(보수/근무환경)을 분리. 위생요인은 불만 제거만, 동기는 만족 증대.",
      conf="maslow-hierarchy", cr="허즈버그는 만족/불만족 분리, 매슬로는 단일 욕구 위계"),
    t("erg-theory", "ERG 이론", "ERG theory", "business", "management_strategy",
      "매슬로 5단계를 존재(E)/관계(R)/성장(G) 3단계로 재구성하고 좌절-퇴행 가능성 인정.",
      conf="maslow-hierarchy", cr="ERG는 3단계 + 퇴행 허용, 매슬로는 5단계 일방향 진행"),
    t("expectancy-theory", "기대이론", "expectancy theory", "business", "management_strategy",
      "동기 = 기대(노력→성과) × 수단(성과→보상) × 유의성(보상의 가치). 브룸이 제안.",
      diff="intermediate",
      conf="equity-theory", cr="기대이론은 보상 기대값 계산, 공정성이론은 타인 대비 비교"),
    t("equity-theory", "공정성이론", "equity theory", "business", "management_strategy",
      "자신의 노력-보상 비율을 타인과 비교해 형평성을 인식하고 행동을 조정한다는 이론.",
      conf="expectancy-theory", cr="공정성은 비교 기반, 기대이론은 기대값 기반"),
    t("transformational-leadership", "변혁적 리더십", "transformational leadership", "business", "management_strategy",
      "비전 제시와 영감으로 부하의 가치관 변화와 잠재력 발휘를 이끄는 리더십.",
      conf="transactional-leadership", cr="변혁적은 가치관 변화 중심, 거래적은 보상-처벌 기반"),
    t("transactional-leadership", "거래적 리더십", "transactional leadership", "business", "management_strategy",
      "성과 달성에 대한 보상과 미달성 처벌의 거래 관계로 부하를 동기부여.",
      conf="transformational-leadership", cr="거래적은 단기 성과 거래, 변혁적은 장기 가치 변화"),
    t("servant-leadership", "서번트 리더십", "servant leadership", "business", "management_strategy",
      "리더가 구성원의 성장과 행복을 우선시하는 봉사 지향적 리더십.",
      conf="transformational-leadership", cr="서번트는 봉사 중심, 변혁적은 비전 중심"),
    t("matrix-organization", "매트릭스 조직", "matrix organization", "business", "management_strategy",
      "기능별과 제품(또는 프로젝트)별 보고체계를 동시에 갖는 이중 권한 구조의 조직.",
      conf="functional-organization", cr="매트릭스는 이중 보고, 기능별 조직은 단일 보고"),
    t("functional-organization", "기능별 조직", "functional organization", "business", "management_strategy",
      "마케팅/생산/재무 등 기능별로 부서를 묶은 전통적 조직 구조.",
      conf="matrix-organization", cr="기능별은 전문성 강조, 매트릭스는 협업 강조"),
    t("divisional-organization", "사업부제 조직", "divisional organization", "business", "management_strategy",
      "제품/지역/고객별로 자율적인 사업단위를 구성한 분권적 조직.",
      conf="functional-organization", cr="사업부제는 자율 단위, 기능별은 중앙집중"),
    t("just-in-time", "JIT", "just-in-time", "business", "management_strategy",
      "필요한 때 필요한 만큼만 생산해 재고를 최소화하는 시스템. 도요타 생산방식의 핵심.",
      diff="intermediate",
      conf="lean-management", cr="JIT는 재고 관점, 린은 낭비 전반의 제거 철학"),
    t("lean-management", "린 경영", "lean management", "business", "management_strategy",
      "낭비(Muda)를 줄이고 가치를 최대화하는 경영 철학. 도요타 생산방식에서 발전.",
      conf="just-in-time", cr="린은 철학 전체, JIT는 재고 관리 기법"),
    t("six-sigma", "식스시그마", "six sigma", "business", "management_strategy",
      "결함을 100만 개 중 3.4개 이하로 줄이는 품질 관리 방법론. DMAIC 사이클 사용.",
      conf="tqm", cr="식스시그마는 통계 기반, TQM은 전사 품질 문화"),
    t("tqm", "전사적 품질경영", "total quality management", "business", "management_strategy",
      "조직 전체가 고객만족을 위해 지속적 품질 개선에 참여하는 경영 철학.",
      aliases=["TQM"],
      conf="six-sigma", cr="TQM은 문화적 접근, 식스시그마는 통계적 도구"),
    t("balanced-scorecard", "균형성과표", "balanced scorecard", "business", "management_strategy",
      "재무/고객/내부프로세스/학습성장 4관점의 성과지표로 전략을 측정·관리하는 도구.",
      aliases=["BSC"], diff="intermediate",
      conf="kpi", cr="BSC는 다관점 프레임워크, KPI는 측정 지표 자체"),
    t("kpi", "핵심성과지표", "key performance indicator", "business", "management_strategy",
      "전략 목표 달성도를 측정하는 핵심 지표.",
      aliases=["KPI"], diff="foundational",
      conf="balanced-scorecard", cr="KPI는 개별 지표, BSC는 KPI를 묶는 프레임"),
    t("benchmarking", "벤치마킹", "benchmarking", "business", "management_strategy",
      "업계 우수 기업의 프로세스/성과를 비교 학습해 개선 목표로 활용하는 기법.",
      conf="balanced-scorecard", cr="벤치마킹은 외부 비교, BSC는 내부 측정 체계"),
    # ═══════════════════ tax (+80) ═══════════════════
    # ── 소득세 (+30) ──
    t("basic-deduction", "기본공제", "basic deduction", "tax", "income_tax",
      "본인 및 부양가족 1인당 연 150만원을 종합소득금액에서 공제하는 인적공제.",
      diff="foundational",
      conf="additional-deduction", cr="기본공제는 모두에게, 추가공제는 경로/장애 등 사유 충족 시"),
    t("additional-deduction", "추가공제", "additional deduction", "tax", "income_tax",
      "경로우대, 장애인, 부녀자, 한부모 등 사유에 해당하는 부양가족에 대한 추가 인적공제.",
      conf="basic-deduction", cr="추가공제는 사유별 가산, 기본공제는 일률 150만원"),
    t("medical-expense-credit", "의료비 세액공제", "medical expense tax credit", "tax", "income_tax",
      "총급여의 3%를 초과한 의료비 일부를 산출세액에서 차감하는 세액공제.",
      conf="tax-credit", cr="의료비 세액공제는 특정 항목, 세액공제는 일반 개념"),
    t("education-expense-credit", "교육비 세액공제", "education expense tax credit", "tax", "income_tax",
      "본인/부양가족의 교육비 일부를 산출세액에서 차감하는 세액공제. 한도가 있다.",
      conf="medical-expense-credit", cr="교육비/의료비 모두 특별세액공제이지만 한도와 대상이 다름"),
    t("donation-credit", "기부금 세액공제", "donation tax credit", "tax", "income_tax",
      "법정/지정 기부금에 대해 일정 비율을 세액에서 공제. 한도 초과분은 이월 가능.",
      conf="medical-expense-credit", cr="기부금/의료비 모두 특별공제군이지만 한도 계산식이 다름"),
    t("pension-income", "연금소득", "pension income", "tax", "income_tax",
      "공적연금, 사적연금 등 정기적으로 수령하는 연금. 연금소득공제 후 종합과세 또는 분리과세.",
      conf="earned-income", cr="연금소득은 퇴직 후 정기 수령, 근로소득은 재직 중 노동 대가"),
    t("other-income", "기타소득", "other income", "tax", "income_tax",
      "상금, 강연료, 원고료 등 일시적·우발적 소득. 60% 또는 80% 필요경비 인정 후 22%로 원천징수.",
      conf="business-income", cr="기타소득은 일시적, 사업소득은 반복적"),
    t("transfer-income-tax", "양도소득세", "transfer income tax", "tax", "income_tax",
      "부동산, 주식, 분양권 등의 양도로 발생한 소득에 대해 부과되는 별도 과세 체계.",
      conf="capital-gains", cr="양도소득세는 세금 자체, 양도소득은 과세 대상 소득"),
    t("one-house-one-household", "1세대 1주택 비과세", "one-house-one-household exemption", "tax", "income_tax",
      "1세대가 1주택을 2년 이상 보유(조정대상지역은 2년 거주)하고 양도가액 12억원 이하면 양도세 비과세.",
      conf="long-term-deduction", cr="1세대1주택은 비과세 조건, 장기보유특별공제는 양도차익 자체 감면"),
    t("long-term-deduction", "장기보유특별공제", "long-term holding deduction", "tax", "income_tax",
      "3년 이상 보유한 부동산 양도 시 양도차익의 일정 비율을 공제하는 제도.",
      conf="one-house-one-household", cr="장기보유공제는 차익 감면, 1세대1주택은 비과세 자체"),
    t("global-progressive-rate", "종합소득세율", "global progressive tax rate", "tax", "income_tax",
      "과세표준 구간별 6%~45%로 적용되는 누진세율 체계.",
      conf="separate-rate", cr="종합세율은 누진, 분리과세 세율은 일정 비율"),
    t("loss-carryforward", "이월결손금", "loss carryforward", "tax", "income_tax",
      "당기 결손금을 이후 사업연도 소득에서 공제할 수 있도록 이월하는 제도. 보통 15년간 가능.",
      conf="loss-carryback", cr="이월결손금은 미래 공제, 결손금 소급공제는 과거 환급"),
    t("loss-carryback", "결손금 소급공제", "loss carryback", "tax", "income_tax",
      "중소기업이 결손금을 직전 사업연도 소득에 적용해 이미 납부한 세액을 환급받는 제도.",
      conf="loss-carryforward", cr="소급공제는 환급, 이월공제는 미래 차감"),
    t("special-deduction", "특별소득공제", "special income deduction", "tax", "income_tax",
      "보험료/주택자금/기부금/근로소득공제 등 특정 사유로 종합소득금액에서 차감하는 공제.",
      conf="basic-deduction", cr="특별공제는 항목별 사유, 기본공제는 인적 일률"),
    t("standard-deduction", "표준세액공제", "standard tax credit", "tax", "income_tax",
      "특별세액공제 항목을 신청하지 않는 근로자에게 13만원을 일률 공제하는 제도.",
      conf="special-deduction", cr="표준세액공제는 일률, 특별소득공제는 항목별"),
    t("housing-fund-deduction", "주택자금 공제", "housing fund deduction", "tax", "income_tax",
      "주택청약저축, 주택임차차입금 원리금 상환 등에 대한 소득공제.",
      conf="special-deduction", cr="주택자금공제는 특별소득공제의 한 종류"),
    t("earned-income-deduction", "근로소득공제", "earned income deduction", "tax", "income_tax",
      "근로소득에서 일정 비율을 자동 차감해 근로소득금액을 산정하는 공제.",
      conf="basic-deduction", cr="근로소득공제는 소득 자체에서, 기본공제는 종합소득금액에서"),
    t("annual-tax-settlement", "연말정산", "year-end tax settlement", "tax", "income_tax",
      "근로소득자에 대해 매월 원천징수한 세액과 연간 산출세액의 차이를 정산하는 절차.",
      diff="foundational",
      conf="final-return", cr="연말정산은 근로소득자 자동, 확정신고는 5월 사업소득 등"),
    t("local-income-tax", "지방소득세", "local income tax", "tax", "income_tax",
      "소득세/법인세의 10%에 해당하는 지방세. 별도 신고 의무는 합산 신고로 처리.",
      conf="comprehensive-taxation", cr="지방소득세는 국세에 부가, 종합과세는 합산 체계"),
    t("tax-base-adjustment", "세무조정", "tax base adjustment", "tax", "corporate_tax",
      "회계상 당기순이익에서 세무상 과세소득으로 전환하기 위한 익금산입/손금산입 등 조정.",
      diff="advanced",
      conf="taxable-income", cr="세무조정은 절차, 과세표준은 결과"),
    t("income-inclusion", "익금산입", "income inclusion", "tax", "corporate_tax",
      "회계상 수익이 아니지만 세무상 익금에 포함시키는 조정.",
      conf="non-income-inclusion", cr="익금산입은 더하기, 익금불산입은 빼기"),
    t("non-income-inclusion", "익금불산입", "non-income inclusion", "tax", "corporate_tax",
      "회계상 수익이지만 세무상 익금에서 제외하는 조정. 자본거래 등.",
      conf="income-inclusion", cr="익금불산입은 익금에서 제외, 익금산입은 추가"),
    t("entertainment-limit", "접대비 한도", "entertainment expense limit", "tax", "corporate_tax",
      "접대비 손금산입 한도. 기본금액 + 수입금액 기준 한도 합산. 초과분은 손금불산입.",
      diff="advanced",
      conf="deductible-expense", cr="접대비 한도는 손금 한정 사유, 손금은 일반 인정 비용"),
    t("donation-limit", "기부금 한도", "donation limit", "tax", "corporate_tax",
      "법정/지정 기부금 손금산입 한도. 종류별로 소득금액의 일정 비율로 제한.",
      conf="entertainment-limit", cr="기부금/접대비 모두 한도 있는 손금이지만 한도 산식이 다름"),
    t("bad-debt-allowance-tax", "대손충당금(세무)", "bad debt allowance (tax)", "tax", "corporate_tax",
      "법인세법상 매출채권 등의 손상에 대비해 손금산입 가능한 충당금 한도.",
      conf="provision", cr="세무상 대손충당금은 손금 한도 규제, 회계상 충당부채는 인식 기준"),
    t("retirement-allowance-tax", "퇴직급여충당금(세무)", "retirement allowance (tax)", "tax", "corporate_tax",
      "퇴직급여 지급에 대비한 충당금. 한도 내 손금산입.",
      conf="defined-benefit-obligation", cr="세무상 퇴직급여충당금은 손금 인정, 회계상 DBO는 추정 측정"),
    t("disguised-act", "부당행위계산 부인", "denial of disguised act", "tax", "corporate_tax",
      "특수관계자와의 거래로 세부담을 부당히 감소시킨 경우 정상 거래로 의제해 과세하는 제도.",
      diff="advanced",
      conf="related-party", cr="부당행위계산 부인은 세무상 부인 제도, 특수관계자는 그 대상"),
    t("foreign-tax-credit", "외국납부세액공제", "foreign tax credit", "tax", "corporate_tax",
      "해외에서 납부한 세금을 국내 산출세액에서 공제하는 제도. 한도가 있다.",
      conf="tax-credit", cr="외국납부세액공제는 국제이중과세 방지, 일반 세액공제는 정책 목적"),
    t("transfer-pricing", "이전가격", "transfer pricing", "tax", "corporate_tax",
      "특수관계 외국법인과의 거래 가격이 정상가격과 다를 경우 세무당국이 조정할 수 있는 제도.",
      diff="advanced",
      conf="disguised-act", cr="이전가격은 국제 거래 가격 조정, 부당행위계산 부인은 국내 특수관계 거래 조정"),
    t("interim-prepayment", "중간예납", "interim prepayment", "tax", "corporate_tax",
      "법인세 사업연도 중간에 직전 사업연도 산출세액의 50% 등을 미리 납부하는 제도.",
      conf="final-return", cr="중간예납은 사전 분납, 확정신고는 정산"),
    # ── 법인세 추가 (15) ──
    t("corporate-tax-rate", "법인세율", "corporate tax rate", "tax", "corporate_tax",
      "과세표준 구간별로 9%/19%/21%/24% 등이 적용되는 법인세 세율 체계.",
      diff="foundational",
      conf="global-progressive-rate", cr="법인세율은 법인 적용, 종합소득세율은 개인 적용"),
    t("capital-and-reserve-adjustment", "자본금과 적립금 조정명세서", "capital and reserve adjustment", "tax", "corporate_tax",
      "법인의 누적 세무조정 잔액을 관리하는 별표. 세무상 자기자본 변동을 추적.",
      diff="advanced",
      conf="tax-base-adjustment", cr="조정명세서는 누적 잔액 관리, 세무조정은 당기 조정 행위"),
    t("dividend-deduction", "수입배당금 익금불산입", "dividend deduction", "tax", "corporate_tax",
      "법인이 다른 법인으로부터 받은 배당금 일부를 익금에서 제외하는 제도. 이중과세 완화.",
      conf="non-income-inclusion", cr="수입배당금 익금불산입은 특정 사유, 익금불산입은 일반 개념"),
    t("ordinary-development-cost", "감가상각비 한도", "depreciation deduction limit", "tax", "corporate_tax",
      "법인세법상 감가상각 손금산입의 상한. 회계상 상각비가 한도를 초과하면 손금불산입.",
      conf="straight-line-depreciation", cr="세무 감가상각 한도는 손금 규제, 정액법은 회계 산식 자체"),
    t("merger-tax-treatment", "합병 세제", "merger tax treatment", "tax", "corporate_tax",
      "적격합병 시 양도손익을 이연, 부적격합병 시 즉시 과세. 회사 재편 시 핵심 검토 항목.",
      diff="advanced",
      conf="corporate-reorganization", cr="합병 세제는 세무 처리, 합병/분할은 거래 자체"),
    t("split-tax-treatment", "분할 세제", "division tax treatment", "tax", "corporate_tax",
      "적격분할 시 양도손익 이연, 부적격분할 시 즉시 과세. 인적분할/물적분할 구분.",
      conf="merger-tax-treatment", cr="분할/합병 세제는 각각 다른 적격요건"),
    t("liquidation-income", "청산소득", "liquidation income", "tax", "corporate_tax",
      "법인 청산 시 잔여재산가액과 자기자본의 차액으로 산출되는 별도 과세소득.",
      diff="advanced",
      conf="capital-gains", cr="청산소득은 법인 청산, 양도소득은 자산 처분"),
    t("anti-tax-haven", "조세피난처 세제", "anti-tax haven rules", "tax", "corporate_tax",
      "조세피난처에 설립된 자회사의 유보소득을 본사 소득에 합산해 과세하는 CFC 규정.",
      diff="advanced",
      conf="transfer-pricing", cr="조세피난처 세제는 자회사 유보소득, 이전가격은 거래가격 조정"),
    t("thin-capitalization", "과소자본세제", "thin capitalization", "tax", "corporate_tax",
      "특수관계 외국법인으로부터 과다 차입 시 일정 비율 초과 이자비용을 손금불산입하는 제도.",
      diff="advanced",
      conf="transfer-pricing", cr="과소자본세제는 자본구조 규제, 이전가격은 거래가격 규제"),
    t("amt", "최저한세", "alternative minimum tax", "tax", "corporate_tax",
      "각종 감면 후에도 최소한 부담해야 하는 세액. 산출세액에 최저한세율을 적용한 금액이 한도.",
      aliases=["AMT"], diff="advanced",
      conf="corporate-tax-rate", cr="최저한세는 감면 후 최소 부담, 법인세율은 기본 적용 세율"),
    t("research-development-credit", "R&D 세액공제", "R&D tax credit", "tax", "corporate_tax",
      "연구·인력개발비에 대한 일정 비율의 세액공제. 신성장동력 R&D는 추가 우대.",
      conf="tax-credit", cr="R&D 세액공제는 정책 인센티브, 일반 세액공제는 광의"),
    t("investment-credit", "투자세액공제", "investment tax credit", "tax", "corporate_tax",
      "특정 자산(생산설비, 안전시설 등) 투자에 대해 일정 비율을 세액에서 공제.",
      conf="research-development-credit", cr="투자세액공제는 자본투자, R&D 세액공제는 인력/연구비"),
    t("penalty-tax", "가산세", "penalty tax", "tax", "corporate_tax",
      "신고불성실, 납부불성실 등 의무 위반에 대해 부과되는 세액. 본세에 가산.",
      conf="amt", cr="가산세는 위반 페널티, 최저한세는 최소 부담"),
    t("tax-evasion-vs-avoidance", "조세회피 vs 조세포탈", "tax avoidance vs evasion", "tax", "corporate_tax",
      "조세회피는 합법적 절세 노력, 조세포탈은 사기 기타 부정행위로 세금을 면탈하는 불법.",
      diff="advanced",
      conf="penalty-tax", cr="조세포탈은 불법 + 형사처벌, 조세회피는 적법한 세무 계획"),
    t("apa", "사전승인약정", "advance pricing agreement", "tax", "corporate_tax",
      "이전가격 산정 방법을 사전에 세무당국과 합의하는 제도. 추후 분쟁 예방.",
      aliases=["APA"], diff="advanced",
      conf="transfer-pricing", cr="APA는 사전 합의, 이전가격은 거래 자체"),
    # ── 부가가치세 (+15) ──
    t("general-vat-payer", "일반과세자", "general VAT payer", "tax", "vat",
      "연 매출 1억400만원 이상 사업자. 세금계산서 발급 의무와 일반 매입세액공제 적용.",
      diff="foundational",
      conf="simplified-vat-payer", cr="일반과세자는 표준 체계, 간이과세자는 간편 적용"),
    t("output-vat", "매출세액", "output VAT", "tax", "vat",
      "사업자가 재화/용역을 공급할 때 거래 상대방에게 거래징수한 부가가치세.",
      formula="매출세액 = 공급가액 × 10%",
      diff="foundational",
      conf="input-vat", cr="매출세액은 받은 세금, 매입세액은 부담한 세금"),
    t("tax-invoice", "세금계산서", "tax invoice", "tax", "vat",
      "사업자가 부가가치세 거래에서 발행하는 공식 증빙. 매입세액공제의 필수 요건.",
      conf="receipt", cr="세금계산서는 사업자 간, 영수증은 최종 소비자 대상"),
    t("electronic-tax-invoice", "전자세금계산서", "electronic tax invoice", "tax", "vat",
      "전자적 방법으로 발급하는 세금계산서. 법인사업자와 일정 매출 이상 개인사업자 의무.",
      conf="tax-invoice", cr="전자/일반 세금계산서 모두 같은 효력이지만 발급 방식이 다름"),
    t("simplified-tax-invoice", "영수증(간이영수증)", "simplified tax invoice", "tax", "vat",
      "최종 소비자에게 발급하는 간이 증빙. 매입세액공제 권리가 제한적.",
      conf="tax-invoice", cr="영수증은 소비자 대상, 세금계산서는 사업자 간 공식 증빙"),
    t("credit-card-sales-slip", "신용카드매출전표", "credit card sales slip", "tax", "vat",
      "신용카드 결제 시 발행되는 거래 증빙. 일정 요건 충족 시 매입세액공제 인정.",
      conf="tax-invoice", cr="신용카드매출전표는 카드결제 증빙, 세금계산서는 일반 공식 증빙"),
    t("bad-debt-vat-credit", "대손세액공제", "bad debt VAT credit", "tax", "vat",
      "이미 매출세액으로 신고·납부한 거래의 매출채권이 대손 확정되면 그 부가가치세를 매출세액에서 차감.",
      diff="advanced",
      conf="output-vat", cr="대손세액공제는 매출세액 사후 조정, 매출세액은 본 거래 세금"),
    t("vat-refund", "환급", "VAT refund", "tax", "vat",
      "매입세액이 매출세액을 초과해 사업자가 부담한 세금을 돌려받는 절차.",
      conf="early-refund", cr="일반환급은 정기 신고 후, 조기환급은 특정 사유로 가속"),
    t("early-refund", "조기환급", "early VAT refund", "tax", "vat",
      "수출, 설비투자, 영세율 적용 등 특정 사유로 부가세 환급을 일반보다 빠르게 받는 제도.",
      conf="vat-refund", cr="조기환급은 가속 환급, 일반환급은 정기 환급"),
    t("preliminary-return", "예정신고", "preliminary VAT return", "tax", "vat",
      "분기마다 매출/매입을 신고·납부하는 절차. 1·3분기는 예정, 2·4분기는 확정.",
      conf="final-vat-return", cr="예정신고는 1·3분기, 확정신고는 2·4분기"),
    t("final-vat-return", "확정신고(VAT)", "final VAT return", "tax", "vat",
      "반기(1월·7월) 말 부가가치세 과세기간의 최종 신고·납부 절차.",
      conf="preliminary-return", cr="확정신고는 반기 마감, 예정신고는 분기 중간"),
    t("non-deductible-input-vat", "매입세액불공제", "non-deductible input VAT", "tax", "vat",
      "사업과 직접 관련 없는 매입, 접대비 등 일정 사유로 매입세액 공제가 인정되지 않는 경우.",
      conf="input-vat", cr="불공제는 공제 인정 안 됨, 매입세액공제는 인정"),
    t("vat-grouping", "사업자단위과세", "VAT business unit taxation", "tax", "vat",
      "복수의 사업장을 가진 사업자가 주된 사업장에서 일괄 신고·납부하는 제도.",
      diff="advanced",
      conf="general-vat-payer", cr="사업자단위과세는 신고 단위 통합, 일반과세자는 적용 체계"),
    t("special-zone-vat", "면세재화", "exempt goods", "tax", "vat",
      "주식, 채권 등 자본거래 또는 의료/교육/주택 임대 등 기초생활 관련 재화·용역의 면세 대상.",
      conf="vat-exemption", cr="면세재화는 대상 목록, 면세는 적용 결과"),
    t("export-vat", "수출재화 영세율", "export zero-rated", "tax", "vat",
      "수출하는 재화에 0% 세율 적용. 매입세액은 환급받을 수 있어 완전면세에 해당.",
      conf="zero-rated-vat", cr="수출재화 영세율은 영세율의 대표 케이스"),
    # ── 기타 (5) ──
    t("inheritance-tax", "상속세", "inheritance tax", "tax", "income_tax",
      "피상속인의 사망으로 상속재산을 취득한 자에게 부과되는 세금. 누진세율 적용.",
      diff="intermediate",
      conf="gift-tax", cr="상속세는 사망 시점, 증여세는 생전 무상 이전"),
    t("gift-tax", "증여세", "gift tax", "tax", "income_tax",
      "타인으로부터 무상으로 재산을 받은 자에게 부과되는 세금. 상속세를 보완하는 역할.",
      conf="inheritance-tax", cr="증여세는 생전 이전, 상속세는 사망 후 이전"),
    t("excessive-property-tax", "종합부동산세", "comprehensive real estate tax", "tax", "income_tax",
      "일정 기준 초과 부동산 보유자에게 누진 부과되는 보유세. 재산세와 별개.",
      conf="transfer-income-tax", cr="종부세는 보유 단계, 양도세는 처분 단계"),
    t("tax-treaty", "조세조약", "tax treaty", "tax", "corporate_tax",
      "이중과세 방지와 탈세 방지를 위해 양국 간 체결하는 협정. 원천징수 세율 우대 등 효과.",
      diff="advanced",
      conf="foreign-tax-credit", cr="조세조약은 협정 체계, 외국납부세액공제는 국내법상 이중과세 방지"),
    t("tax-savings-account", "절세 금융상품", "tax-saving financial product", "tax", "income_tax",
      "ISA, 연금저축 등 일정 요건 충족 시 비과세/저율분리과세 혜택이 부여되는 상품군.",
      conf="separate-taxation", cr="절세 금융상품은 비과세 혜택, 분리과세는 세율 체계"),
    # ═══════════════════ economics (+87) ═══════════════════
    # ── 미시 (+50) ──
    t("demand-curve", "수요곡선", "demand curve", "economics", "micro_economics",
      "가격과 수요량의 관계를 나타내는 곡선. 일반적으로 우하향.",
      diff="foundational",
      conf="supply-curve", cr="수요는 가격↓→수량↑, 공급은 가격↑→수량↑"),
    t("supply-curve", "공급곡선", "supply curve", "economics", "micro_economics",
      "가격과 공급량의 관계를 나타내는 곡선. 일반적으로 우상향.",
      diff="foundational",
      conf="demand-curve", cr="공급곡선은 우상향, 수요곡선은 우하향"),
    t("market-equilibrium", "시장균형", "market equilibrium", "economics", "micro_economics",
      "수요량과 공급량이 일치하는 가격·수량 조합. 초과수요/초과공급이 없는 상태.",
      diff="foundational",
      conf="equilibrium-price", cr="시장균형은 상태, 균형가격은 그 상태의 가격"),
    t("equilibrium-price", "균형가격", "equilibrium price", "economics", "micro_economics",
      "수요와 공급이 만나는 가격. 시장청산 가격.",
      conf="market-equilibrium", cr="균형가격은 가격 한 점, 시장균형은 그 상태 전반"),
    t("utility-function", "효용함수", "utility function", "economics", "micro_economics",
      "재화 묶음에서 얻는 만족도를 수치로 나타낸 함수.",
      conf="marginal-utility", cr="효용함수는 총효용, 한계효용은 단위 추가 시의 증분"),
    t("marginal-utility", "한계효용", "marginal utility", "economics", "micro_economics",
      "재화 1단위 추가 소비로 얻는 효용의 증분.",
      formula="MU = ∂U / ∂Q",
      conf="diminishing-marginal-utility", cr="한계효용은 측정값, 한계효용체감은 일반적 성질"),
    t("diminishing-marginal-utility", "한계효용체감의 법칙", "law of diminishing marginal utility", "economics", "micro_economics",
      "소비량이 증가할수록 추가 단위의 효용이 점차 감소한다는 법칙.",
      conf="marginal-utility", cr="체감의 법칙은 변화 방향, 한계효용은 그 측정값"),
    t("indifference-curve", "무차별곡선", "indifference curve", "economics", "micro_economics",
      "동일한 효용을 주는 재화 조합을 연결한 곡선. 일반적으로 원점에 볼록.",
      conf="budget-line", cr="무차별곡선은 선호, 예산선은 제약"),
    t("budget-line", "예산선", "budget line", "economics", "micro_economics",
      "주어진 소득과 가격으로 살 수 있는 재화 조합의 경계. 우하향 직선.",
      formula="P1·Q1 + P2·Q2 = M",
      conf="indifference-curve", cr="예산선은 가용 제약, 무차별곡선은 선호 표현"),
    t("marginal-rate-of-substitution", "한계대체율", "marginal rate of substitution", "economics", "micro_economics",
      "한 재화를 1단위 더 얻기 위해 포기할 수 있는 다른 재화의 양. 무차별곡선의 기울기 절댓값.",
      aliases=["MRS"],
      conf="marginal-rate-of-transformation", cr="MRS는 소비자 선호 기울기, MRT는 생산 가능성 곡선 기울기"),
    t("marginal-rate-of-transformation", "한계변환율", "marginal rate of transformation", "economics", "micro_economics",
      "한 재화 생산을 1단위 늘릴 때 포기해야 하는 다른 재화 생산량. 생산가능곡선 기울기.",
      aliases=["MRT"],
      conf="marginal-rate-of-substitution", cr="MRT는 생산, MRS는 소비"),
    t("production-function", "생산함수", "production function", "economics", "micro_economics",
      "투입요소 양과 산출량의 기술적 관계.",
      diff="foundational",
      conf="marginal-product", cr="생산함수는 전체 관계, 한계생산물은 변화율"),
    t("marginal-product", "한계생산물", "marginal product", "economics", "micro_economics",
      "투입요소 1단위 추가 시 산출량의 증분.",
      formula="MP = ∂Q / ∂L",
      conf="marginal-rate-of-technical-substitution", cr="MP는 한 요소 증분, MRTS는 두 요소 대체율"),
    t("marginal-rate-of-technical-substitution", "한계기술대체율", "marginal rate of technical substitution", "economics", "micro_economics",
      "동일 산출량을 유지하면서 한 투입요소를 1단위 더 늘릴 때 줄일 수 있는 다른 요소의 양.",
      aliases=["MRTS"], diff="advanced",
      conf="marginal-rate-of-substitution", cr="MRTS는 생산 등량곡선 기울기, MRS는 소비 무차별곡선 기울기"),
    t("returns-to-scale", "규모에 대한 수익", "returns to scale", "economics", "micro_economics",
      "모든 투입요소를 동일 비율 증가시킬 때 산출 증가율. 증가/감소/일정 3유형.",
      diff="intermediate",
      conf="economies-of-scale", cr="규모수익은 모든 투입 동일 증가, 규모의 경제는 평균비용 감소"),
    t("economies-of-scale", "규모의 경제", "economies of scale", "economics", "micro_economics",
      "산출량이 증가할 때 단위당 평균비용이 감소하는 현상.",
      conf="returns-to-scale", cr="규모의 경제는 비용 측면, 규모수익은 산출 측면"),
    t("diseconomies-of-scale", "규모의 불경제", "diseconomies of scale", "economics", "micro_economics",
      "산출량이 너무 커져 단위당 평균비용이 증가하는 현상.",
      conf="economies-of-scale", cr="규모의 불경제는 평균비용 증가, 규모의 경제는 감소"),
    t("profit-maximization", "이윤극대화", "profit maximization", "economics", "micro_economics",
      "기업이 추구하는 목표. 한계수입(MR)과 한계비용(MC)이 같은 산출 수준에서 달성.",
      formula="MR = MC",
      diff="foundational",
      conf="cost-minimization", cr="이윤극대화는 산출 결정, 비용극소화는 동일 산출의 투입 조합 결정"),
    t("monopolistic-competition", "독점적 경쟁", "monopolistic competition", "economics", "micro_economics",
      "유사하지만 차별화된 상품을 다수 기업이 공급하는 시장구조. 단기 이윤 가능, 장기 0 이윤.",
      conf="oligopoly", cr="독점적 경쟁은 다수 + 차별화, 과점은 소수 기업"),
    t("oligopoly", "과점", "oligopoly", "economics", "micro_economics",
      "소수의 기업이 시장을 지배하는 구조. 상호 의존성과 전략적 행동이 특징.",
      conf="monopolistic-competition", cr="과점은 소수 기업, 독점적 경쟁은 다수 기업"),
    t("prisoners-dilemma", "죄수의 딜레마", "prisoner's dilemma", "economics", "micro_economics",
      "협력 시 모두 이익이지만 개별 합리성으로는 배신이 우월전략인 게임이론의 대표 사례.",
      diff="intermediate",
      conf="nash-equilibrium", cr="죄수의 딜레마는 게임 예시, 내쉬균형은 일반 균형 개념"),
    t("nash-equilibrium", "내쉬균형", "Nash equilibrium", "economics", "micro_economics",
      "모든 참여자가 다른 사람의 전략을 주어진 것으로 보고 자신의 전략을 바꿀 유인이 없는 상태.",
      conf="prisoners-dilemma", cr="내쉬균형은 일반 균형 정의, 죄수의 딜레마는 그 한 예"),
    t("dominant-strategy", "지배전략", "dominant strategy", "economics", "micro_economics",
      "상대방의 어떤 전략에 대해서도 자신에게 가장 유리한 전략.",
      conf="nash-equilibrium", cr="지배전략은 항상 우월, 내쉬균형은 상호 최적 응답"),
    t("price-discrimination", "가격차별", "price discrimination", "economics", "micro_economics",
      "동일 상품을 고객별/시점별 다른 가격으로 판매. 1차/2차/3차로 구분.",
      diff="intermediate",
      conf="monopoly", cr="가격차별은 독점/독점적경쟁에서 가능한 전략"),
    t("first-degree-price-discrimination", "1차 가격차별", "first-degree price discrimination", "economics", "micro_economics",
      "각 고객의 지불 의향 가격을 정확히 알아 그대로 부과. 완전 가격차별.",
      conf="third-degree-price-discrimination", cr="1차는 개인별 완전 차별, 3차는 그룹별 차별"),
    t("third-degree-price-discrimination", "3차 가격차별", "third-degree price discrimination", "economics", "micro_economics",
      "고객 그룹별로 다른 가격을 부과. 학생할인 등이 예시.",
      conf="first-degree-price-discrimination", cr="3차는 그룹별, 1차는 개인별"),
    t("externality", "외부효과", "externality", "economics", "micro_economics",
      "시장가격에 반영되지 않은 거래 당사자 외 영향. 긍정적/부정적으로 구분.",
      diff="intermediate",
      conf="public-good", cr="외부효과는 시장 실패 한 형태, 공공재는 또 다른 시장 실패 형태"),
    t("public-good", "공공재", "public good", "economics", "micro_economics",
      "비배제성과 비경합성을 가진 재화. 국방, 가로등 등. 시장이 효율적으로 공급하지 못함.",
      conf="externality", cr="공공재는 비배제+비경합, 외부효과는 시장 외 영향"),
    t("coase-theorem", "코즈의 정리", "Coase theorem", "economics", "micro_economics",
      "거래비용이 0이고 재산권이 명확하면 외부효과는 협상으로 효율적 해결이 가능하다는 정리.",
      diff="advanced",
      conf="externality", cr="코즈 정리는 외부효과의 해결책, 외부효과는 문제 자체"),
    t("asymmetric-information", "정보의 비대칭", "asymmetric information", "economics", "micro_economics",
      "거래 당사자 간 정보 보유량 차이로 발생하는 시장 실패. 역선택과 도덕적 해이 야기.",
      conf="adverse-selection", cr="정보 비대칭은 원인, 역선택/도덕적 해이는 결과"),
    t("adverse-selection", "역선택", "adverse selection", "economics", "micro_economics",
      "거래 전 숨겨진 특성 때문에 위험도 높은 자가 자기 선택해 시장에 남는 현상. 중고차 시장 등.",
      conf="moral-hazard", cr="역선택은 거래 전(숨은 특성), 도덕적 해이는 거래 후(숨은 행동)"),
    t("moral-hazard", "도덕적 해이", "moral hazard", "economics", "micro_economics",
      "거래 후 숨은 행동으로 위험을 키우는 현상. 보험 가입 후 위험 회피 노력 감소 등.",
      conf="adverse-selection", cr="도덕적 해이는 거래 후 행동, 역선택은 거래 전 자기선택"),
    t("signaling", "신호 발송", "signaling", "economics", "micro_economics",
      "정보를 가진 측이 자신의 우월성을 비용 있는 행동으로 보여주는 행위. 학위 취득 등.",
      conf="screening", cr="신호는 우월측 자발 발신, 스크리닝은 열위측 능동 분류"),
    t("screening", "스크리닝", "screening", "economics", "micro_economics",
      "정보가 부족한 측이 거래 상대를 분류해 정보 비대칭을 줄이는 행위. 보험사 등급 분류 등.",
      conf="signaling", cr="스크리닝은 부족측 능동 분류, 신호는 우월측 발신"),
    t("deadweight-loss", "사중손실", "deadweight loss", "economics", "micro_economics",
      "시장 비효율성으로 소비자/생산자 잉여 합이 줄어든 손실. 세금/독점/가격통제 등이 원인.",
      conf="consumer-surplus", cr="사중손실은 손실 부분, 소비자잉여는 후생의 한 측면"),
    t("compensating-wage", "보상격차", "compensating wage differential", "economics", "micro_economics",
      "위험/불쾌한 직업에 추가 지급되는 임금 격차.",
      conf="human-capital", cr="보상격차는 업무 특성 기반, 인적자본은 노동자 특성 기반"),
    t("human-capital", "인적자본", "human capital", "economics", "micro_economics",
      "교육과 훈련을 통해 축적된 노동자의 생산성. 임금 격차의 주요 원인.",
      conf="compensating-wage", cr="인적자본은 노동자 능력, 보상격차는 업무 특성 차이"),
    t("monopsony", "수요독점", "monopsony", "economics", "micro_economics",
      "특정 재화/노동의 유일한 구매자가 시장을 지배하는 구조.",
      conf="monopoly", cr="수요독점은 단일 구매자, 공급독점은 단일 판매자"),
    t("rent", "지대", "rent", "economics", "micro_economics",
      "공급이 고정된 생산요소(토지 등)에 지급되는 대가. 잉여로 해석.",
      conf="profit", cr="지대는 고정공급 요소 보수, 이윤은 기업가의 잔여 수익"),
    t("cournot-model", "쿠르노 모형", "Cournot model", "economics", "micro_economics",
      "과점기업이 산출량을 동시에 결정하고 상대방 산출량을 주어진 것으로 가정하는 게임.",
      diff="advanced",
      conf="bertrand-model", cr="쿠르노는 산출량 경쟁, 베르트랑은 가격 경쟁"),
    t("bertrand-model", "베르트랑 모형", "Bertrand model", "economics", "micro_economics",
      "과점기업이 가격을 동시에 결정하는 게임. 동질재라면 가격이 한계비용까지 떨어짐.",
      diff="advanced",
      conf="cournot-model", cr="베르트랑은 가격 경쟁, 쿠르노는 산출량 경쟁"),
    t("game-theory", "게임이론", "game theory", "economics", "micro_economics",
      "상호 의존적 의사결정 상황에서 전략적 행동을 분석하는 도구. 내쉬, 쿠르노, 죄수의 딜레마 등.",
      conf="nash-equilibrium", cr="게임이론은 분석 도구 전체, 내쉬균형은 그 핵심 개념"),
    t("monopoly-deadweight", "독점의 사회적 비용", "deadweight loss of monopoly", "economics", "micro_economics",
      "독점가격이 한계비용보다 높아 소비자잉여 일부가 사라지는 손실.",
      conf="deadweight-loss", cr="독점 사중손실은 시장구조 원인, 사중손실은 일반 현상"),
    t("antitrust", "공정거래법", "antitrust", "economics", "micro_economics",
      "독과점 행위와 불공정 거래를 규제하는 법 체계. 시장 효율성 확보.",
      conf="monopoly", cr="공정거래법은 규제 수단, 독점은 규제 대상"),
    t("rent-seeking", "지대추구 행위", "rent-seeking", "economics", "micro_economics",
      "생산적 활동 없이 정부의 보호나 특권을 얻으려는 자원 낭비 행위.",
      diff="advanced",
      conf="rent", cr="지대추구는 활동, 지대는 그로 인한 수익"),
    t("pareto-optimum", "파레토 최적", "Pareto optimum", "economics", "micro_economics",
      "누군가의 효용을 늘리려면 다른 누군가의 효용을 줄여야 하는 자원배분 상태. 효율의 기본 정의.",
      diff="intermediate",
      conf="market-equilibrium", cr="파레토 최적은 효율 개념, 시장균형은 수요·공급 결과"),
    t("first-welfare-theorem", "후생경제학 제1정리", "first welfare theorem", "economics", "micro_economics",
      "완전경쟁시장의 균형은 파레토 최적을 달성한다는 정리.",
      diff="advanced",
      conf="pareto-optimum", cr="제1정리는 시장→최적, 파레토 최적은 그 결과"),
    t("second-welfare-theorem", "후생경제학 제2정리", "second welfare theorem", "economics", "micro_economics",
      "적절한 초기 자원 재분배 후 시장에 맡기면 어떤 파레토 최적이든 달성 가능하다는 정리.",
      diff="advanced",
      conf="first-welfare-theorem", cr="제2정리는 분배 후 시장 정당화, 제1정리는 시장 자체 효율성"),
    t("ramsey-pricing", "램지 가격설정", "Ramsey pricing", "economics", "micro_economics",
      "독점기업이 사회 후생을 극대화하면서 적자를 면할 수 있도록 가격탄력성에 반비례해 마진을 매기는 규칙.",
      diff="advanced",
      conf="price-discrimination", cr="램지 가격은 규제 도구, 가격차별은 이윤 극대화 도구"),
    # ── 거시 (+30) ──
    t("business-cycle", "경기변동", "business cycle", "economics", "macro_economics",
      "경제 활동이 호황과 불황 사이를 주기적으로 반복하는 현상.",
      diff="foundational",
      conf="inflation", cr="경기변동은 산출 변동, 인플레이션은 물가 변동"),
    t("inflation", "인플레이션", "inflation", "economics", "macro_economics",
      "물가 수준이 지속적으로 상승하는 현상.",
      diff="foundational",
      conf="deflation", cr="인플레이션은 물가 상승, 디플레이션은 하락"),
    t("deflation", "디플레이션", "deflation", "economics", "macro_economics",
      "물가 수준이 지속적으로 하락하는 현상. 경기 침체와 동반되면 위험.",
      conf="inflation", cr="디플레이션은 하락, 디스인플레이션은 상승률 둔화"),
    t("stagflation", "스태그플레이션", "stagflation", "economics", "macro_economics",
      "경기 침체와 인플레이션이 동시에 발생하는 현상. 공급 충격이 원인.",
      conf="inflation", cr="스태그플레이션은 인플레이션 + 침체, 일반 인플레이션은 호황과 결합"),
    t("unemployment-rate", "실업률", "unemployment rate", "economics", "macro_economics",
      "경제활동인구 중 실업자 비율.",
      formula="실업률 = 실업자 / 경제활동인구",
      diff="foundational",
      conf="natural-unemployment-rate", cr="실업률은 측정값, 자연실업률은 장기 균형값"),
    t("natural-unemployment-rate", "자연실업률", "natural rate of unemployment", "economics", "macro_economics",
      "물가 압력 없이 유지될 수 있는 장기 균형 실업률. 마찰적 + 구조적 실업.",
      conf="unemployment-rate", cr="자연실업률은 균형, 실업률은 현재값"),
    t("frictional-unemployment", "마찰적 실업", "frictional unemployment", "economics", "macro_economics",
      "구직과 일자리 매칭 과정에서 자연 발생하는 단기 실업.",
      conf="structural-unemployment", cr="마찰적은 단기 매칭 비용, 구조적은 산업 변화로 인한 장기"),
    t("structural-unemployment", "구조적 실업", "structural unemployment", "economics", "macro_economics",
      "산업 구조 변화로 노동자 기술과 수요 기술 불일치로 발생하는 장기 실업.",
      conf="frictional-unemployment", cr="구조적은 산업 변화, 마찰적은 일시 매칭"),
    t("cyclical-unemployment", "경기적 실업", "cyclical unemployment", "economics", "macro_economics",
      "경기 침체로 수요 부족이 발생해 일어나는 실업. 경기 회복으로 줄어듦.",
      conf="natural-unemployment-rate", cr="경기적 실업은 단기 변동, 자연실업률은 장기 균형"),
    t("phillips-curve", "필립스 곡선", "Phillips curve", "economics", "macro_economics",
      "인플레이션율과 실업률의 역의 관계를 보여주는 곡선. 단기에는 우하향.",
      diff="intermediate",
      conf="natural-unemployment-rate", cr="필립스 곡선은 인플레-실업 관계, 자연실업률은 그 수직선 위치"),
    t("money-demand", "화폐수요", "money demand", "economics", "macro_economics",
      "거래/예비/투기 동기로 화폐를 보유하려는 수요. 케인즈가 체계화.",
      conf="money-supply", cr="화폐수요는 수요 측, 통화공급은 공급 측"),
    t("monetary-base", "본원통화", "monetary base", "economics", "macro_economics",
      "현금과 은행의 중앙은행 예치금 합계. 신용창출의 출발점.",
      conf="money-supply", cr="본원통화는 중앙은행이 직접 통제, 통화량은 은행의 신용창출 결과"),
    t("money-multiplier", "통화승수", "money multiplier", "economics", "macro_economics",
      "본원통화 1단위 증가가 통화량을 얼마나 늘리는지의 배수.",
      formula="m = 1 / 지급준비율",
      conf="monetary-base", cr="통화승수는 배수, 본원통화는 그 배수가 적용되는 기초"),
    t("reserve-ratio", "지급준비율", "reserve ratio", "economics", "macro_economics",
      "은행이 예금 중 일정 비율을 중앙은행에 적립해야 하는 비율. 통화공급 조절 수단.",
      conf="money-multiplier", cr="지급준비율은 정책 변수, 통화승수는 그 결과"),
    t("rational-expectations", "합리적 기대", "rational expectations", "economics", "macro_economics",
      "경제주체가 가능한 모든 정보를 활용해 체계적으로 오류를 범하지 않는 기대 형성.",
      diff="advanced",
      conf="adaptive-expectations", cr="합리적 기대는 정보 활용, 적응적 기대는 과거 추세 외삽"),
    t("adaptive-expectations", "적응적 기대", "adaptive expectations", "economics", "macro_economics",
      "과거 관측치에 가중치를 두어 점진적으로 조정하는 기대 형성. 합리적 기대의 대안.",
      conf="rational-expectations", cr="적응적은 과거 기반, 합리적은 정보 종합"),
    t("keynesian-economics", "케인즈 경제학", "Keynesian economics", "economics", "macro_economics",
      "총수요 부족이 경기 침체의 원인이며 적극적 재정·통화 정책이 필요하다는 학파.",
      diff="intermediate",
      conf="classical-economics", cr="케인즈는 수요 중시, 고전학파는 공급 중시"),
    t("classical-economics", "고전학파", "classical economics", "economics", "macro_economics",
      "시장이 자동조절되며 장기적으로 완전고용이 달성된다는 학파. 세이의 법칙 강조.",
      conf="keynesian-economics", cr="고전은 시장 자율, 케인즈는 정부 개입"),
    t("solow-growth-model", "솔로우 성장모형", "Solow growth model", "economics", "macro_economics",
      "자본축적과 기술진보로 1인당 산출 증가를 설명하는 신고전파 성장모형.",
      diff="advanced",
      conf="endogenous-growth", cr="솔로우는 외생적 기술진보, 내생적 성장은 R&D 등 내생화"),
    t("endogenous-growth", "내생적 성장이론", "endogenous growth theory", "economics", "macro_economics",
      "지식 축적, 인적자본, R&D 등 모형 내부 요인으로 장기 성장률을 설명하는 이론.",
      conf="solow-growth-model", cr="내생적 성장은 기술 내생화, 솔로우는 외생"),
    t("government-spending-multiplier", "정부지출 승수", "government spending multiplier", "economics", "macro_economics",
      "정부지출 1단위 증가가 GDP를 얼마나 늘리는지의 배수.",
      formula="승수 = 1 / (1 - 한계소비성향)",
      conf="tax-multiplier", cr="정부지출 승수와 세금 승수는 부호와 크기가 다름"),
    t("crowding-out", "구축효과", "crowding-out", "economics", "macro_economics",
      "정부지출 증가로 이자율이 올라 민간투자가 감소하는 효과.",
      conf="government-spending-multiplier", cr="구축효과는 승수 효과를 약화시키는 요인"),
    t("automatic-stabilizer", "자동안정장치", "automatic stabilizer", "economics", "macro_economics",
      "경기 변동에 따라 자동으로 작동하는 재정 메커니즘. 누진세, 실업급여 등.",
      conf="fiscal-policy", cr="자동안정장치는 자동, 재정정책은 재량적"),
    t("foreign-exchange-market", "외환시장", "foreign exchange market", "economics", "macro_economics",
      "외환이 거래되는 시장. 환율이 결정되는 장.",
      diff="foundational",
      conf="exchange-rate", cr="외환시장은 장소, 환율은 그 시장의 가격"),
    t("ppp", "구매력평가설", "purchasing power parity", "economics", "macro_economics",
      "양국의 환율은 양국 물가수준의 비율로 결정된다는 환율 결정이론.",
      aliases=["PPP"], diff="intermediate",
      conf="interest-rate-parity", cr="PPP는 물가 기반, 이자율평가는 금리 기반"),
    t("interest-rate-parity", "이자율평가", "interest rate parity", "economics", "macro_economics",
      "양국 금리 차이가 환율의 기대 변동률과 같아진다는 환율 결정이론.",
      conf="ppp", cr="이자율평가는 단기 금융 흐름, PPP는 장기 무역 흐름"),
    t("current-account", "경상수지", "current account", "economics", "macro_economics",
      "재화·서비스·소득·이전 거래의 수지. 국제수지표의 한 항목.",
      conf="capital-account", cr="경상수지는 실물 거래, 자본수지는 금융 거래"),
    t("capital-account", "자본수지", "capital account", "economics", "macro_economics",
      "자본 자산의 이전과 비생산·비금융자산 매매를 기록하는 국제수지 항목.",
      conf="current-account", cr="자본수지는 금융 자본 이동, 경상수지는 재화·서비스"),
    t("floating-exchange-rate", "변동환율제도", "floating exchange rate", "economics", "macro_economics",
      "외환시장 수요·공급에 의해 환율이 자유롭게 결정되는 제도.",
      conf="fixed-exchange-rate", cr="변동환율은 시장 결정, 고정환율은 정부 고정"),
    t("fixed-exchange-rate", "고정환율제도", "fixed exchange rate", "economics", "macro_economics",
      "정부나 중앙은행이 환율을 일정 수준으로 고정시키는 제도.",
      conf="floating-exchange-rate", cr="고정환율은 안정 + 자율성 제약, 변동은 변동 + 자율성"),
    # ── 국제 (+7) ──
    t("comparative-advantage", "비교우위", "comparative advantage", "economics", "macro_economics",
      "기회비용이 더 낮은 재화 생산에 특화하는 것이 양국에 유리하다는 무역 이론.",
      conf="absolute-advantage", cr="비교우위는 기회비용 기준, 절대우위는 절대 생산성 기준"),
    t("absolute-advantage", "절대우위", "absolute advantage", "economics", "macro_economics",
      "동일 자원으로 더 많이 생산할 수 있는 능력. 아담 스미스가 제안.",
      conf="comparative-advantage", cr="절대우위는 생산성 절대치, 비교우위는 기회비용"),
    t("heckscher-ohlin", "헥셔-올린 정리", "Heckscher-Ohlin theorem", "economics", "macro_economics",
      "국가가 풍부한 부존자원을 집약적으로 사용하는 재화를 수출한다는 무역 이론.",
      diff="advanced",
      conf="comparative-advantage", cr="헥셔-올린은 부존자원 기반, 비교우위는 기술 기반"),
    t("tariff", "관세", "tariff", "economics", "macro_economics",
      "수입품에 부과되는 세금. 국내산업 보호 효과 + 사회후생 감소 효과.",
      conf="non-tariff-barrier", cr="관세는 가격 장벽, 비관세장벽은 규제/쿼터 등"),
    t("non-tariff-barrier", "비관세장벽", "non-tariff barrier", "economics", "macro_economics",
      "관세 외 방법(쿼터, 기술 규제, 보조금 등)으로 수입을 제한하는 정책.",
      conf="tariff", cr="비관세장벽은 비가격 규제, 관세는 가격 부담"),
    t("free-trade-agreement", "자유무역협정", "free trade agreement", "economics", "macro_economics",
      "체결국 간 관세와 무역장벽을 제거하거나 완화하는 협정.",
      aliases=["FTA"], diff="foundational",
      conf="tariff", cr="FTA는 관세 철폐 협정, 관세는 그 대상 정책"),
    t("wto", "세계무역기구", "World Trade Organization", "economics", "macro_economics",
      "다자간 무역 규범 운영과 분쟁 해결을 담당하는 국제기구. GATT 후속.",
      aliases=["WTO"],
      conf="free-trade-agreement", cr="WTO는 다자간, FTA는 양자/지역 협정"),
    # ═══════════════════ corporate_law (+90) ═══════════════════
    # ── 상법 일반 (+15) ──
    t("commercial-act-general", "당연상행위", "absolute commercial act", "corporate_law", "commercial_general",
      "상법 제46조에서 열거한 영업 행위. 행위 자체로 상행위로 인정된다.",
      conf="auxiliary-commercial-act", cr="당연상행위는 영업 본체, 보조적 상행위는 영업을 돕는 행위"),
    t("auxiliary-commercial-act", "보조적 상행위", "auxiliary commercial act", "corporate_law", "commercial_general",
      "상인이 영업을 위해 하는 행위. 영업 본체는 아니지만 상행위로 의제됨.",
      conf="commercial-act-general", cr="보조적 상행위는 영업을 돕는, 당연상행위는 영업 본체"),
    t("commercial-agent", "상사대리", "commercial agency", "corporate_law", "commercial_general",
      "상인의 영업 일정 부분을 대리하는 관계. 본인-대리인 책임이 민법과 다른 면이 있다.",
      conf="agency-by-estoppel", cr="상사대리는 정식 대리, 표현대리는 외관 신뢰 보호"),
    t("commission-agent", "위탁매매업", "commission agency", "corporate_law", "commercial_general",
      "자기 명의로 타인의 계산으로 물건 매매를 영업으로 하는 자. 자기 책임으로 거래.",
      diff="intermediate",
      conf="commercial-agent", cr="위탁매매업은 자기 명의 + 타인 계산, 상사대리는 본인 명의"),
    t("carrier", "운송인", "carrier", "corporate_law", "commercial_general",
      "물건 또는 사람을 운반하는 영업을 하는 자. 운송계약상 책임에 대한 특별 규정.",
      conf="warehouse-keeper", cr="운송인은 이동, 창고업자는 보관"),
    t("warehouse-keeper", "창고업자", "warehouse keeper", "corporate_law", "commercial_general",
      "타인을 위해 물건을 보관하는 영업을 하는 자.",
      conf="carrier", cr="창고업은 보관 영업, 운송은 이동 영업"),
    t("commercial-lien", "상사유치권", "commercial lien", "corporate_law", "commercial_general",
      "상인 간 영업 관련 거래에서 채권 확보를 위해 점유 목적물을 유치할 수 있는 권리. 민사유치권보다 요건 완화.",
      conf="commercial-act-general", cr="상사유치권은 권리, 상행위는 그 권리가 발생하는 거래"),
    t("commercial-limitation-period", "상사 소멸시효", "commercial prescription", "corporate_law", "commercial_general",
      "상행위로 인한 채권은 5년의 단기 소멸시효가 적용된다(상법 제64조).",
      conf="commercial-act-general", cr="상사 소멸시효는 상행위 채권에 한정"),
    t("dormant-partnership", "익명조합", "dormant partnership", "corporate_law", "commercial_general",
      "익명조합원이 영업자에게 출자하고 영업자가 자기 명의로 영업하며 이익을 분배하는 관계.",
      conf="anonymous-association", cr="익명조합은 출자 + 분배, 합명회사는 법인 형태"),
    t("commercial-bookkeeping", "상업장부", "commercial bookkeeping", "corporate_law", "commercial_general",
      "상인이 영업과 재산 상태를 명백히 하기 위해 작성·보존해야 하는 장부. 회계장부와 대차대조표 포함.",
      conf="commercial-register", cr="상업장부는 회계 기록, 상업등기는 공시 등기"),
    t("commercial-employee", "상업사용인", "commercial employee", "corporate_law", "commercial_general",
      "상인을 위해 영업에 관한 재판상·재판외 모든 행위를 할 수 있는 사용인. 지배인이 대표적.",
      conf="commercial-agent", cr="상업사용인은 사용 관계, 상사대리는 대리 관계"),
    t("branch-manager", "지배인", "branch manager", "corporate_law", "commercial_general",
      "본점 또는 지점의 영업을 포괄적으로 대리할 권한을 가진 상업사용인.",
      conf="commercial-employee", cr="지배인은 포괄대리권 보유, 일반 상업사용인은 제한적"),
    t("commercial-property", "영업 양도", "transfer of business", "corporate_law", "commercial_general",
      "영업의 일체(자산, 부채, 영업권 등)를 일괄 양도하는 거래. 양수인은 양도인의 채무를 인수.",
      diff="advanced",
      conf="corporate-reorganization", cr="영업 양도는 자산 이전, 합병은 법인 자체 결합"),
    t("trademark", "상표", "trademark", "corporate_law", "commercial_general",
      "상품을 표시하기 위해 사용하는 표지. 상표법으로 보호되며 상호와 구분.",
      conf="trade-name", cr="상표는 상품 표시, 상호는 영업주체 표시"),
    t("commercial-arbitration", "상사중재", "commercial arbitration", "corporate_law", "commercial_general",
      "상사 분쟁을 법원이 아닌 중재인에게 맡겨 해결하는 절차. 신속성과 비공개가 장점.",
      conf="commercial-limitation-period", cr="상사중재는 분쟁 해결, 소멸시효는 권리 행사 기한"),
    # ── 회사법 (+50) ──
    t("ordinary-partnership", "합명회사", "ordinary partnership", "corporate_law", "company_law",
      "사원 전원이 회사 채무에 무한 연대 책임을 지는 인적 회사. 사원 간 신뢰 기반.",
      conf="limited-partnership", cr="합명은 모두 무한책임, 합자는 무한+유한 혼합"),
    t("limited-partnership", "합자회사", "limited partnership", "corporate_law", "company_law",
      "무한책임사원과 유한책임사원으로 구성된 회사.",
      conf="ordinary-partnership", cr="합자는 책임 혼합, 합명은 모두 무한책임"),
    t("limited-liability-company", "유한회사", "limited liability company", "corporate_law", "company_law",
      "사원 전원이 출자액 한도로 책임지는 인적·물적 절충 회사. 폐쇄적 운영.",
      aliases=["LLC"],
      conf="stock-company", cr="유한회사는 폐쇄적 운영, 주식회사는 공개 가능"),
    t("stock-company", "주식회사", "stock corporation", "corporate_law", "company_law",
      "자본을 주식으로 분할하고 주주는 출자액 한도로 책임지는 물적 회사. CPA 1차의 주요 대상.",
      diff="foundational",
      conf="limited-liability-company", cr="주식회사는 자본 분할 + 양도성, 유한회사는 폐쇄적"),
    t("limited-liability-co-llp", "유한책임회사", "LLP", "corporate_law", "company_law",
      "출자자 모두 유한책임이면서 내부 자율을 폭넓게 허용한 회사 형태. 2011년 도입.",
      diff="advanced",
      conf="limited-liability-company", cr="유한책임회사는 자율 강화, 유한회사는 전통 형태"),
    t("promotion-establishment", "발기설립", "promotion establishment", "corporate_law", "company_law",
      "발기인이 발행 주식 전부를 인수해 회사를 설립하는 방식.",
      conf="public-offering-establishment", cr="발기설립은 발기인 인수, 모집설립은 외부 모집"),
    t("public-offering-establishment", "모집설립", "public offering establishment", "corporate_law", "company_law",
      "발기인이 일부 주식을 인수하고 나머지는 외부에서 모집하는 설립 방식.",
      conf="promotion-establishment", cr="모집설립은 외부 모집 포함, 발기설립은 발기인만"),
    t("articles-of-incorporation", "정관", "articles of incorporation", "corporate_law", "company_law",
      "회사 조직과 활동의 기본 규칙을 정한 자치 규범. 절대적·상대적·임의적 기재사항.",
      diff="intermediate",
      conf="commercial-register", cr="정관은 회사 내부 규범, 상업등기는 외부 공시"),
    t("abnormal-establishment-item", "변태설립사항", "abnormal establishment items", "corporate_law", "company_law",
      "현물출자, 재산인수, 발기인 보수 등 일반 설립과 다른 사항. 정관 기재 + 검사인 조사.",
      diff="advanced",
      conf="articles-of-incorporation", cr="변태설립사항은 정관의 특수 기재, 정관은 일반 자치규범"),
    t("promoter-liability", "발기인의 책임", "promoter liability", "corporate_law", "company_law",
      "회사 설립 시 발기인이 부담하는 자본충실 의무 + 출자 부실에 대한 인수담보책임 등.",
      conf="abnormal-establishment-item", cr="발기인 책임은 인적 책임, 변태설립은 객관적 사항"),
    t("preferred-stock", "우선주", "preferred stock", "corporate_law", "company_law",
      "이익배당이나 잔여재산분배에서 보통주보다 우선하는 주식. 의결권 제한이 일반적.",
      conf="common-stock", cr="우선주는 우선 분배 + 의결권 제한, 보통주는 표준"),
    t("common-stock", "보통주", "common stock", "corporate_law", "company_law",
      "표준적 주식. 이익배당과 의결권에서 우선/제한이 없다.",
      conf="preferred-stock", cr="보통주는 표준, 우선주는 분배 우선 + 의결권 제한"),
    t("class-shares", "종류주식", "class shares", "corporate_law", "company_law",
      "이익배당, 의결권, 상환, 전환 등 권리 내용이 다른 주식. 우선주/상환주/전환주 등.",
      conf="preferred-stock", cr="종류주식은 일반 개념, 우선주는 그 한 유형"),
    t("share-transfer", "주식 양도", "share transfer", "corporate_law", "company_law",
      "주주가 자신의 주식을 다른 자에게 이전하는 행위. 원칙적 자유, 정관으로 제한 가능.",
      conf="name-on-book-transfer", cr="주식 양도는 거래, 명의개서는 명부 변경 절차"),
    t("name-on-book-transfer", "명의개서", "transfer on shareholders book", "corporate_law", "company_law",
      "주식 양도 후 회사 명부에 양수인을 기재하는 절차. 회사 대항 요건.",
      conf="share-transfer", cr="명의개서는 절차, 주식 양도는 실체 거래"),
    t("treasury-shares-law", "자기주식 취득", "treasury share acquisition", "corporate_law", "company_law",
      "회사가 자기 발행 주식을 취득하는 행위. 상법상 일정 한도와 절차 요건이 있다.",
      conf="treasury-stock", cr="자기주식 취득은 상법상 행위, 자기주식은 회계 항목"),
    t("share-cancellation", "주식 소각", "share cancellation", "corporate_law", "company_law",
      "회사가 보유한 자기주식을 절차에 따라 소멸시키는 행위. 자본금 감소 효과.",
      conf="treasury-shares-law", cr="주식 소각은 소멸, 자기주식 취득은 보유 단계"),
    t("capital-reduction", "감자", "capital reduction", "corporate_law", "company_law",
      "회사 자본금을 감소시키는 행위. 결손보전 등 목적. 채권자보호 절차 필요.",
      diff="advanced",
      conf="share-cancellation", cr="감자는 자본금 변동 총칭, 주식 소각은 그 한 방법"),
    t("right-of-shareholder-meeting", "주주의 권한", "shareholder rights", "corporate_law", "company_law",
      "이익배당청구권, 잔여재산분배청구권, 의결권 등 주주가 보유하는 권리의 총체.",
      conf="board-of-directors", cr="주주 권한은 소유자 권리, 이사회는 경영진의 의사결정"),
    t("voting-right", "의결권", "voting right", "corporate_law", "company_law",
      "주주총회에서 행사하는 결의권. 보통주는 1주 1의결권 원칙.",
      conf="right-of-shareholder-meeting", cr="의결권은 한 권리, 주주 권한은 그 모음"),
    t("residual-claim", "잔여재산분배청구권", "residual claim", "corporate_law", "company_law",
      "회사 청산 시 부채를 모두 갚고 남은 재산을 주주가 지분 비율로 분배받을 권리.",
      conf="dividend-payment", cr="잔여재산분배는 청산 시점, 이익배당은 정상 영업 중"),
    t("derivative-suit", "주주대표소송", "derivative suit", "corporate_law", "company_law",
      "이사 등의 위법 행위로 회사가 손해를 입었을 때 주주가 회사를 대표해 제기하는 소송.",
      diff="advanced",
      conf="right-of-shareholder-meeting", cr="주주대표소송은 권리 행사 수단, 주주 권한은 그 권리 모음"),
    t("shareholder-proposal", "주주제안권", "shareholder proposal right", "corporate_law", "company_law",
      "일정 지분 이상 보유 주주가 주주총회 의안을 제안할 수 있는 권리.",
      conf="cumulative-voting", cr="주주제안권은 의안 제안, 집중투표제는 이사 선임 방식"),
    t("cumulative-voting", "집중투표제", "cumulative voting", "corporate_law", "company_law",
      "2명 이상의 이사를 동시에 선임할 때 1주당 의결권을 한 후보에 집중 가능한 제도.",
      diff="advanced",
      conf="voting-right", cr="집중투표제는 의결권 행사 방식, 의결권은 권리 자체"),
    t("extraordinary-meeting", "임시주주총회", "extraordinary shareholders meeting", "corporate_law", "company_law",
      "정기총회 외에 필요에 따라 소집되는 주주총회. 일정 지분 보유 주주가 소집을 청구 가능.",
      conf="shareholders-meeting", cr="임시주총은 비정기, 정기주총은 결산 후 정기"),
    t("ordinary-resolution", "보통결의", "ordinary resolution", "corporate_law", "company_law",
      "주주총회에서 출석 의결권 과반수와 발행주식수의 1/4 이상으로 가결되는 결의.",
      diff="intermediate",
      conf="special-resolution", cr="보통결의는 단순 다수, 특별결의는 가중 다수"),
    t("special-resolution", "특별결의", "special resolution", "corporate_law", "company_law",
      "주주총회에서 출석 의결권 2/3 이상과 발행주식수 1/3 이상으로 가결되는 가중 결의. 정관 변경, 합병 등.",
      conf="ordinary-resolution", cr="특별결의는 가중요건, 보통결의는 일반요건"),
    t("director-appointment", "이사 선임", "director appointment", "corporate_law", "company_law",
      "주주총회 보통결의로 이사를 선임하는 행위. 임기는 3년 이내.",
      conf="director-dismissal", cr="이사 선임은 보통결의, 해임은 특별결의"),
    t("director-dismissal", "이사 해임", "director dismissal", "corporate_law", "company_law",
      "주주총회 특별결의로 이사를 해임. 정당한 이유 없이 해임 시 손해배상 책임.",
      conf="director-appointment", cr="해임은 특별결의 + 손해배상 가능, 선임은 보통결의"),
    t("outside-director", "사외이사", "outside director", "corporate_law", "company_law",
      "회사의 상무에 종사하지 않으면서 회사 경영을 객관적으로 감독하는 이사. 상장회사 일정 비율 이상 의무.",
      conf="board-of-directors", cr="사외이사는 이사회의 한 유형, 이사회는 전체 기관"),
    t("director-liability", "이사의 책임", "director liability", "corporate_law", "company_law",
      "이사가 법령/정관에 위반하거나 임무를 게을리해 회사에 손해를 끼친 때의 손해배상 책임.",
      conf="derivative-suit", cr="이사 책임은 책임 자체, 대표소송은 추궁 수단"),
    t("director-compensation", "이사의 보수", "director compensation", "corporate_law", "company_law",
      "이사가 받는 보수. 정관 또는 주주총회 결의로 정한다.",
      conf="director-appointment", cr="이사 보수는 대가, 선임은 신분 결정"),
    t("audit-committee", "감사위원회", "audit committee", "corporate_law", "company_law",
      "이사회 내 3인 이상의 위원으로 구성된 감사 기능 기관. 일정 규모 상장회사는 설치 의무.",
      conf="statutory-auditor", cr="감사위원회는 위원회 형태, 감사는 단독 기관"),
    t("listing-special-rules", "상장회사 특례", "listed company special rules", "corporate_law", "company_law",
      "상장회사에 한해 적용되는 사외이사 비율, 집중투표제, 감사위원회 등 추가 규제.",
      conf="audit-committee", cr="상장회사 특례는 규제 묶음, 감사위원회는 그 중 하나"),
    t("share-exchange", "주식의 포괄적 교환", "share exchange", "corporate_law", "company_law",
      "한 회사가 다른 회사의 모든 주식을 자기 주식으로 교환해 100% 자회사로 만드는 거래.",
      diff="advanced",
      conf="share-transfer-comprehensive", cr="주식교환은 기존 회사 간, 주식이전은 새 모회사 설립"),
    t("share-transfer-comprehensive", "주식의 포괄적 이전", "share transfer", "corporate_law", "company_law",
      "기존 회사 주주가 새로 설립되는 모회사에 주식을 일괄 이전해 지주회사 구조를 만드는 거래.",
      diff="advanced",
      conf="share-exchange", cr="주식이전은 새 모회사 설립, 주식교환은 기존 회사 간"),
    t("dissolution", "회사 해산", "company dissolution", "corporate_law", "company_law",
      "회사의 법인격이 소멸하기 시작하는 사유 발생. 청산 절차로 이어진다.",
      conf="liquidation", cr="해산은 시작, 청산은 절차 진행"),
    t("liquidation", "청산", "liquidation", "corporate_law", "company_law",
      "해산 후 재산 정리, 채무 변제, 잔여재산 분배까지의 절차.",
      conf="dissolution", cr="청산은 절차, 해산은 그 진입 사유"),
    t("bankruptcy", "파산", "bankruptcy", "corporate_law", "company_law",
      "채무자가 채무를 변제할 수 없는 상태로 법원이 선고하는 절차. 회생절차와 구분.",
      conf="rehabilitation", cr="파산은 청산형, 회생은 재건형"),
    t("rehabilitation", "회생절차", "rehabilitation procedure", "corporate_law", "company_law",
      "재정적 어려움에 빠진 회사를 회생시키기 위한 법원 주관 절차. 채무 조정과 영업 계속이 핵심.",
      conf="bankruptcy", cr="회생은 재건 목적, 파산은 청산 목적"),
    t("foreign-company", "외국회사", "foreign company", "corporate_law", "company_law",
      "외국법에 따라 설립된 회사. 국내 영업소 설치 시 등기 의무.",
      conf="commercial-register", cr="외국회사는 주체, 상업등기는 절차"),
    t("controlling-shareholder", "지배주주", "controlling shareholder", "corporate_law", "company_law",
      "회사 의사결정에 사실상 지배력을 행사할 수 있는 주주. 일반적으로 30% 이상 보유 또는 사실상 지배.",
      conf="non-controlling-interest", cr="지배주주는 지배측, 비지배지분은 그 외 주주"),
    t("controlling-shareholder-loyalty", "지배주주의 충실의무", "controlling shareholder fiduciary duty", "corporate_law", "company_law",
      "지배주주가 회사와 다른 주주에 대해 부담하는 의무. 부당한 사적 이익 추구 금지.",
      diff="advanced",
      conf="controlling-shareholder", cr="충실의무는 의무 자체, 지배주주는 그 의무 주체"),
    t("piercing-corporate-veil", "법인격 부인", "piercing the corporate veil", "corporate_law", "company_law",
      "회사를 지배주주의 도구로 남용한 경우 법인격을 부정하고 지배주주에게 책임을 묻는 법리.",
      diff="advanced",
      conf="controlling-shareholder", cr="법인격 부인은 책임 추궁 법리, 지배주주는 그 대상"),
    t("squeeze-out", "지배주주의 매도청구권", "squeeze-out", "corporate_law", "company_law",
      "95% 이상 보유 지배주주가 잔여 주주의 주식을 강제 매수할 수 있는 권리.",
      diff="advanced",
      conf="controlling-shareholder", cr="매도청구권은 지배주주의 권리, 지배주주는 그 보유자"),
    t("sell-back-right", "주주의 매수청구권", "shareholder appraisal right", "corporate_law", "company_law",
      "합병/분할 등 중대 결의에 반대한 주주가 자신의 주식을 공정한 가격에 매수해 달라고 청구할 권리.",
      conf="squeeze-out", cr="매수청구권은 반대 주주 권리, 매도청구권은 지배주주 권리"),
    t("interim-dividend", "중간배당", "interim dividend", "corporate_law", "company_law",
      "사업연도 중 1회 한도로 정관에 따라 이사회 결의로 실시할 수 있는 배당.",
      conf="dividend-payment", cr="중간배당은 1회/년 + 이사회 결의, 일반배당은 주총 결의"),
    t("stock-dividend", "주식배당", "stock dividend", "corporate_law", "company_law",
      "이익배당을 현금이 아닌 신주로 지급하는 방식. 자본전입 효과.",
      conf="dividend-payment", cr="주식배당은 자본전입, 현금배당은 사외유출"),
    t("director-self-dealing", "이사의 자기거래", "director self-dealing", "corporate_law", "company_law",
      "이사가 회사와 직접 또는 제3자를 통해 거래하는 행위. 이사회 승인 필요.",
      diff="advanced",
      conf="director-liability", cr="자기거래는 거래 행위, 이사 책임은 위반 시 책임"),
    t("director-competition-prohibition", "이사의 경업금지의무", "director non-compete duty", "corporate_law", "company_law",
      "이사가 회사의 영업부류에 속한 거래를 하거나 동종 다른 회사 임원이 되려면 이사회 승인 필요.",
      conf="director-self-dealing", cr="경업금지는 동종 영업, 자기거래는 회사와의 직접 거래"),
    # ── 상사매매/유가증권 (+20) ──
    t("commercial-sale", "상사매매", "commercial sale", "corporate_law", "commercial_general",
      "상인 간 매매에서 적용되는 특별 규정. 매수인의 검사·통지 의무 등.",
      conf="ordinary-sale", cr="상사매매는 상인 간, 일반매매는 민사"),
    t("inspection-and-notice", "검사·통지의무", "duty of inspection and notice", "corporate_law", "commercial_general",
      "상사매매에서 매수인은 인도받은 물건을 지체 없이 검사하고 하자 발견 시 통지해야 한다.",
      conf="commercial-sale", cr="검사·통지의무는 매수인 의무, 상사매매는 그 의무가 적용되는 거래"),
    t("promissory-note", "약속어음", "promissory note", "corporate_law", "commercial_general",
      "발행인이 자기 채무로서 일정 금액을 지급하기로 약속하는 어음.",
      conf="bill-of-exchange", cr="약속어음은 자기 지급 약속, 환어음은 제3자에게 지급 명령"),
    t("bill-of-exchange", "환어음", "bill of exchange", "corporate_law", "commercial_general",
      "발행인이 제3자(지급인)에게 일정 금액을 수취인에게 지급할 것을 명령하는 어음.",
      conf="promissory-note", cr="환어음은 제3자 지급 명령, 약속어음은 자기 지급 약속"),
    t("check", "수표", "check", "corporate_law", "commercial_general",
      "발행인이 은행에 일정 금액을 수취인에게 지급할 것을 위탁하는 유가증권. 어음과 다른 별도 법제.",
      conf="bill-of-exchange", cr="수표는 은행 지급 + 일람불, 환어음은 일반 지급인 + 만기 가능"),
    t("endorsement", "배서", "endorsement", "corporate_law", "commercial_general",
      "유가증권의 권리를 양도하기 위해 증서 뒤면에 기명·날인 또는 서명하는 행위.",
      conf="acceptance", cr="배서는 양도, 인수는 지급 확약"),
    t("acceptance", "인수", "acceptance", "corporate_law", "commercial_general",
      "환어음의 지급인이 지급 의무를 부담하기로 약속하는 행위.",
      conf="endorsement", cr="인수는 지급 약속, 배서는 권리 양도"),
    t("delivery-of-securities", "주식 양도방식", "share delivery", "corporate_law", "company_law",
      "주권 발행 회사는 주권 교부로, 주권 미발행 회사는 의사표시로 주식이 양도된다.",
      conf="name-on-book-transfer", cr="주권 교부는 권리 이전, 명의개서는 회사 대항 요건"),
    t("registered-share", "기명주식", "registered share", "corporate_law", "company_law",
      "주주명부에 주주 이름이 기재되는 주식. 한국 상법상 원칙적 형태.",
      conf="bearer-share", cr="기명주식은 명의 등록, 무기명주식은 익명"),
    t("bearer-share", "무기명주식", "bearer share", "corporate_law", "company_law",
      "주권 소지자가 주주로 인정되는 주식. 한국에서는 2014년 폐지.",
      conf="registered-share", cr="무기명은 소지자 권리, 기명은 명부 등록"),
    t("debenture", "사채(상법)", "debenture", "corporate_law", "company_law",
      "주식회사가 채권자에게 발행하는 채무증권. 일반사채, 전환사채, 신주인수권부사채 등.",
      conf="convertible-bond", cr="사채는 채무증권 총칭, 전환사채는 그 한 종류"),
    t("debenture-issue", "사채 발행", "debenture issue", "corporate_law", "company_law",
      "주식회사가 사채를 발행하는 절차. 이사회 결의로 가능, 일정 한도 내.",
      conf="debenture", cr="사채 발행은 행위, 사채는 결과 증권"),
    t("convertible-bond-issue", "전환사채 발행", "convertible bond issue", "corporate_law", "company_law",
      "주식 전환권이 부여된 사채 발행. 정관 또는 이사회 결의로 발행 가능.",
      conf="bond-with-warrant-issue", cr="CB 발행은 전환권, BW 발행은 신주인수권"),
    t("bond-with-warrant-issue", "신주인수권부사채 발행", "bond with warrant issue", "corporate_law", "company_law",
      "신주인수권이 부여된 사채 발행. 사채와 인수권을 분리할 수 있다.",
      conf="convertible-bond-issue", cr="BW는 신주인수권만, CB는 사채 자체 전환"),
    t("securities-issuance-disclosure", "증권 발행 공시", "securities issuance disclosure", "corporate_law", "company_law",
      "공모로 증권을 발행할 때 자본시장법상 증권신고서 등의 공시 의무.",
      diff="advanced",
      conf="listing-special-rules", cr="발행 공시는 자본시장법, 상장 특례는 상법"),
    t("disclosure-of-major-shareholder", "대량보유 보고", "5% rule disclosure", "corporate_law", "company_law",
      "상장사 주식을 5% 이상 보유하면 5영업일 내 보고해야 하는 자본시장법상 의무.",
      aliases=["5%룰"], diff="advanced",
      conf="securities-issuance-disclosure", cr="대량보유 보고는 보유 변동 공시, 발행공시는 발행 시점 공시"),
    t("short-swing-profit", "단기매매차익 반환", "short-swing profit", "corporate_law", "company_law",
      "내부자가 6개월 내 매수·매도(또는 매도·매수)로 얻은 차익은 회사에 반환해야 하는 의무.",
      diff="advanced",
      conf="insider-trading", cr="단기매매차익 반환은 객관적 책임, 내부자거래는 부정 정보 이용"),
    t("insider-trading", "내부자거래", "insider trading", "corporate_law", "company_law",
      "회사 내부자가 미공개 중요 정보를 이용해 주식을 매매하는 행위. 금지된다.",
      conf="short-swing-profit", cr="내부자거래는 정보 이용, 단기매매차익은 시점만 보는 객관적 규제"),
    t("preemptive-right-disposition", "신주인수권 처분", "preemptive right disposition", "corporate_law", "company_law",
      "주주가 신주인수권을 행사하지 않고 양도하거나 포기하는 행위.",
      conf="preemptive-right", cr="처분은 양도/포기 행위, 신주인수권은 권리 자체"),
    t("share-listing", "주식 상장", "share listing", "corporate_law", "company_law",
      "주식을 거래소 시장에 등록해 공개 거래되도록 하는 절차. 상장요건 충족 필요.",
      conf="listing-special-rules", cr="상장은 절차, 상장회사 특례는 상장 후 적용 규제"),
    # ── 기타 (+5) ──
    t("fair-trade-act", "공정거래법", "fair trade act", "corporate_law", "commercial_general",
      "독과점/불공정거래 행위/대규모기업집단 등을 규제하는 법. 회사법과 별개의 행정 규제 체계.",
      conf="antitrust", cr="공정거래법은 한국법, antitrust는 일반 개념"),
    t("merger-notification", "기업결합 신고", "merger notification", "corporate_law", "commercial_general",
      "일정 규모 이상의 기업결합 시 공정거래위원회에 사전·사후 신고해야 하는 의무.",
      conf="fair-trade-act", cr="기업결합 신고는 절차, 공정거래법은 그 근거 법"),
    t("anonymous-association", "익명조합과 합자조합", "anonymous and limited partnership", "corporate_law", "commercial_general",
      "익명조합은 익명 출자 + 영업자 운영, 합자조합은 무한책임 + 유한책임 조합원 결합 형태.",
      diff="advanced",
      conf="dormant-partnership", cr="익명조합/합자조합 모두 비법인 조합, 합자회사는 회사 형태"),
    t("commercial-trust", "신탁", "commercial trust", "corporate_law", "commercial_general",
      "위탁자가 재산을 수탁자에게 이전하고 수익자를 위해 관리/처분하게 하는 법률관계.",
      conf="dormant-partnership", cr="신탁은 재산 이전 + 관리, 익명조합은 출자 + 분배"),
    t("electronic-securities", "전자증권", "electronic securities", "corporate_law", "company_law",
      "실물 증서 없이 전자 등록으로 권리 이전·관리되는 증권 제도. 2019년 시행.",
      conf="registered-share", cr="전자증권은 전자 등록, 기명주식은 명부 등록(실물 가능)"),
]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for term in TERMS:
        path = OUT_DIR / f"{term['term_id']}.term.json"
        with path.open("w", encoding="utf-8", newline="\n") as f:
            json.dump(term, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print(f"wrote {len(TERMS)} new term files to {OUT_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
